// Code generated by gotemplate. DO NOT EDIT.

package mock_block

import (
	"fmt"

	"github.com/eosspark/eos-go/common/container"
	"github.com/eosspark/eos-go/common/container/multiindex"
)

// template type OrderedIndex(FinalIndex,FinalNode,SuperIndex,SuperNode,Value,Key,KeyFunc,Comparator,Multiply)

// OrderedIndex holds elements of the red-black tree
type ByLibNum struct {
	super *TestIndexBase // index on the OrderedIndex, IndexBase is the last super index
	final *TestIndex     // index under the OrderedIndex, MultiIndex is the final index

	Root *ByLibNumNode
	size int
}

func (tree *ByLibNum) init(final *TestIndex) {
	tree.final = final
	tree.super = &TestIndexBase{}
	tree.super.init(final)
}

func (tree *ByLibNum) clear() {
	tree.Clear()
	tree.super.clear()
}

/*generic class*/

/*generic class*/

// OrderedIndexNode is a single element within the tree
type ByLibNumNode struct {
	Key    ByLibNumComposite
	super  *TestIndexBaseNode
	final  *TestIndexNode
	color  colorByLibNum
	Left   *ByLibNumNode
	Right  *ByLibNumNode
	Parent *ByLibNumNode
}

/*generic class*/

/*generic class*/

func (node *ByLibNumNode) value() *ValueType {
	return node.super.value()
}

type colorByLibNum bool

const (
	blackByLibNum, redByLibNum colorByLibNum = true, false
)

func (tree *ByLibNum) Insert(v ValueType) (IteratorByLibNum, bool) {
	fn, res := tree.final.insert(v)
	if res {
		return tree.makeIterator(fn), true
	}
	return tree.End(), false
}

func (tree *ByLibNum) insert(v ValueType, fn *TestIndexNode) (*ByLibNumNode, bool) {
	key := ByLibNumKeyFunc(v)

	node, res := tree.put(key)
	if !res {
		container.Logger.Warn("#ordered index insert failed")
		return nil, false
	}
	sn, res := tree.super.insert(v, fn)
	if res {
		node.super = sn
		node.final = fn
		return node, true
	}
	tree.remove(node)
	return nil, false
}

func (tree *ByLibNum) Erase(iter IteratorByLibNum) (itr IteratorByLibNum) {
	itr = iter
	itr.Next()
	tree.final.erase(iter.node.final)
	return
}

func (tree *ByLibNum) Erases(first, last IteratorByLibNum) {
	for first != last {
		first = tree.Erase(first)
	}
}

func (tree *ByLibNum) erase(n *ByLibNumNode) {
	tree.remove(n)
	tree.super.erase(n.super)
	n.super = nil
	n.final = nil
}

func (tree *ByLibNum) erase_(iter multiindex.IteratorType) {
	if itr, ok := iter.(IteratorByLibNum); ok {
		tree.Erase(itr)
	} else {
		tree.super.erase_(iter)
	}
}

func (tree *ByLibNum) Modify(iter IteratorByLibNum, mod func(*ValueType)) bool {
	if _, b := tree.final.modify(mod, iter.node.final); b {
		return true
	}
	return false
}

func (tree *ByLibNum) modify(n *ByLibNumNode) (*ByLibNumNode, bool) {
	n.Key = ByLibNumKeyFunc(*n.value())

	if !tree.inPlace(n) {
		tree.remove(n)
		node, res := tree.put(n.Key)
		if !res {
			container.Logger.Warn("#ordered index modify failed")
			tree.super.erase(n.super)
			return nil, false
		}

		//n.Left = node.Left
		//if n.Left != nil {
		//	n.Left.Parent = n
		//}
		//n.Right = node.Right
		//if n.Right != nil {
		//	n.Right.Parent = n
		//}
		//n.Parent = node.Parent
		//if n.Parent != nil {
		//	if n.Parent.Left == node {
		//		n.Parent.Left = n
		//	} else {
		//		n.Parent.Right = n
		//	}
		//} else {
		//	tree.Root = n
		//}
		node.super = n.super
		node.final = n.final
		n = node
	}

	if sn, res := tree.super.modify(n.super); !res {
		tree.remove(n)
		return nil, false
	} else {
		n.super = sn
	}

	return n, true
}

func (tree *ByLibNum) modify_(iter multiindex.IteratorType, mod func(*ValueType)) bool {
	if itr, ok := iter.(IteratorByLibNum); ok {
		return tree.Modify(itr, mod)
	} else {
		return tree.super.modify_(iter, mod)
	}
}

// Get searches the node in the tree by key and returns its value or nil if key is not found in tree.
// Second return parameter is true if key was found, otherwise false.
// Key should adhere to the comparator's type assertion, otherwise method panics.
func (tree *ByLibNum) Find(key ByLibNumComposite) IteratorByLibNum {
	if true {
		lower := tree.LowerBound(key)
		if !lower.IsEnd() && ByLibNumCompare(key, lower.Key()) == 0 {
			return lower
		}
		return tree.End()
	} else {
		if node := tree.lookup(key); node != nil {
			return IteratorByLibNum{tree, node, betweenByLibNum}
		}
		return tree.End()
	}
}

// LowerBound returns an iterator pointing to the first element that is not less than the given key.
// Complexity: O(log N).
func (tree *ByLibNum) LowerBound(key ByLibNumComposite) IteratorByLibNum {
	result := tree.End()
	node := tree.Root

	if node == nil {
		return result
	}

	for {
		if ByLibNumCompare(key, node.Key) > 0 {
			if node.Right != nil {
				node = node.Right
			} else {
				return result
			}
		} else {
			result.node = node
			result.position = betweenByLibNum
			if node.Left != nil {
				node = node.Left
			} else {
				return result
			}
		}
	}
}

// UpperBound returns an iterator pointing to the first element that is greater than the given key.
// Complexity: O(log N).
func (tree *ByLibNum) UpperBound(key ByLibNumComposite) IteratorByLibNum {
	result := tree.End()
	node := tree.Root

	if node == nil {
		return result
	}

	for {
		if ByLibNumCompare(key, node.Key) >= 0 {
			if node.Right != nil {
				node = node.Right
			} else {
				return result
			}
		} else {
			result.node = node
			result.position = betweenByLibNum
			if node.Left != nil {
				node = node.Left
			} else {
				return result
			}
		}
	}
}

// Remove remove the node from the tree by key.
// Key should adhere to the comparator's type assertion, otherwise method panics.
func (tree *ByLibNum) Remove(key ByLibNumComposite) {
	if true {
		for lower := tree.LowerBound(key); lower.position != endByLibNum; {
			if ByLibNumCompare(lower.Key(), key) == 0 {
				node := lower.node
				lower.Next()
				tree.remove(node)
			} else {
				break
			}
		}
	} else {
		node := tree.lookup(key)
		tree.remove(node)
	}
}

func (tree *ByLibNum) put(key ByLibNumComposite) (*ByLibNumNode, bool) {
	var insertedNode *ByLibNumNode
	if tree.Root == nil {
		// Assert key is of comparator's type for initial tree
		ByLibNumCompare(key, key)
		tree.Root = &ByLibNumNode{Key: key, color: redByLibNum}
		insertedNode = tree.Root
	} else {
		node := tree.Root
		loop := true
		if true {
			for loop {
				compare := ByLibNumCompare(key, node.Key)
				switch {
				case compare < 0:
					if node.Left == nil {
						node.Left = &ByLibNumNode{Key: key, color: redByLibNum}
						insertedNode = node.Left
						loop = false
					} else {
						node = node.Left
					}
				case compare >= 0:
					if node.Right == nil {
						node.Right = &ByLibNumNode{Key: key, color: redByLibNum}
						insertedNode = node.Right
						loop = false
					} else {
						node = node.Right
					}
				}
			}
		} else {
			for loop {
				compare := ByLibNumCompare(key, node.Key)
				switch {
				case compare == 0:
					node.Key = key
					return node, false
				case compare < 0:
					if node.Left == nil {
						node.Left = &ByLibNumNode{Key: key, color: redByLibNum}
						insertedNode = node.Left
						loop = false
					} else {
						node = node.Left
					}
				case compare > 0:
					if node.Right == nil {
						node.Right = &ByLibNumNode{Key: key, color: redByLibNum}
						insertedNode = node.Right
						loop = false
					} else {
						node = node.Right
					}
				}
			}
		}
		insertedNode.Parent = node
	}
	tree.insertCase1(insertedNode)
	tree.size++

	return insertedNode, true
}

func (tree *ByLibNum) swapNode(node *ByLibNumNode, pred *ByLibNumNode) {
	if node == pred {
		return
	}

	tmp := ByLibNumNode{color: pred.color, Left: pred.Left, Right: pred.Right, Parent: pred.Parent}

	pred.color = node.color
	node.color = tmp.color

	pred.Right = node.Right
	if pred.Right != nil {
		pred.Right.Parent = pred
	}
	node.Right = tmp.Right
	if node.Right != nil {
		node.Right.Parent = node
	}

	if pred.Parent == node {
		pred.Left = node
		node.Left = tmp.Left
		if node.Left != nil {
			node.Left.Parent = node
		}

		pred.Parent = node.Parent
		if pred.Parent != nil {
			if pred.Parent.Left == node {
				pred.Parent.Left = pred
			} else {
				pred.Parent.Right = pred
			}
		} else {
			tree.Root = pred
		}
		node.Parent = pred

	} else {
		pred.Left = node.Left
		if pred.Left != nil {
			pred.Left.Parent = pred
		}
		node.Left = tmp.Left
		if node.Left != nil {
			node.Left.Parent = node
		}

		pred.Parent = node.Parent
		if pred.Parent != nil {
			if pred.Parent.Left == node {
				pred.Parent.Left = pred
			} else {
				pred.Parent.Right = pred
			}
		} else {
			tree.Root = pred
		}

		node.Parent = tmp.Parent
		if node.Parent != nil {
			if node.Parent.Left == pred {
				node.Parent.Left = node
			} else {
				node.Parent.Right = node
			}
		} else {
			tree.Root = node
		}
	}
}

func (tree *ByLibNum) remove(node *ByLibNumNode) {
	var child *ByLibNumNode
	if node == nil {
		return
	}
	if node.Left != nil && node.Right != nil {
		pred := node.Left.maximumNode()
		tree.swapNode(node, pred)
	}
	if node.Left == nil || node.Right == nil {
		if node.Right == nil {
			child = node.Left
		} else {
			child = node.Right
		}
		if node.color == blackByLibNum {
			node.color = nodeColorByLibNum(child)
			tree.deleteCase1(node)
		}
		tree.replaceNode(node, child)
		if node.Parent == nil && child != nil {
			child.color = blackByLibNum
		}
	}
	tree.size--
}

func (tree *ByLibNum) lookup(key ByLibNumComposite) *ByLibNumNode {
	node := tree.Root
	for node != nil {
		compare := ByLibNumCompare(key, node.Key)
		switch {
		case compare == 0:
			return node
		case compare < 0:
			node = node.Left
		case compare > 0:
			node = node.Right
		}
	}
	return nil
}

// Empty returns true if tree does not contain any nodes
func (tree *ByLibNum) Empty() bool {
	return tree.size == 0
}

// Size returns number of nodes in the tree.
func (tree *ByLibNum) Size() int {
	return tree.size
}

// Keys returns all keys in-order
func (tree *ByLibNum) Keys() []ByLibNumComposite {
	keys := make([]ByLibNumComposite, tree.size)
	it := tree.Iterator()
	for i := 0; it.Next(); i++ {
		keys[i] = it.Key()
	}
	return keys
}

// Values returns all values in-order based on the key.
func (tree *ByLibNum) Values() []ValueType {
	values := make([]ValueType, tree.size)
	it := tree.Iterator()
	for i := 0; it.Next(); i++ {
		values[i] = it.Value()
	}
	return values
}

// Left returns the left-most (min) node or nil if tree is empty.
func (tree *ByLibNum) Left() *ByLibNumNode {
	var parent *ByLibNumNode
	current := tree.Root
	for current != nil {
		parent = current
		current = current.Left
	}
	return parent
}

// Right returns the right-most (max) node or nil if tree is empty.
func (tree *ByLibNum) Right() *ByLibNumNode {
	var parent *ByLibNumNode
	current := tree.Root
	for current != nil {
		parent = current
		current = current.Right
	}
	return parent
}

// Clear removes all nodes from the tree.
func (tree *ByLibNum) Clear() {
	tree.Root = nil
	tree.size = 0
}

// String returns a string representation of container
func (tree *ByLibNum) String() string {
	str := "OrderedIndex\n"
	if !tree.Empty() {
		outputByLibNum(tree.Root, "", true, &str)
	}
	return str
}

func (node *ByLibNumNode) String() string {
	if !node.color {
		return fmt.Sprintf("(%v,%v)", node.Key, "red")
	}
	return fmt.Sprintf("(%v)", node.Key)
}

func outputByLibNum(node *ByLibNumNode, prefix string, isTail bool, str *string) {
	if node.Right != nil {
		newPrefix := prefix
		if isTail {
			newPrefix += "│   "
		} else {
			newPrefix += "    "
		}
		outputByLibNum(node.Right, newPrefix, false, str)
	}
	*str += prefix
	if isTail {
		*str += "└── "
	} else {
		*str += "┌── "
	}
	*str += node.String() + "\n"
	if node.Left != nil {
		newPrefix := prefix
		if isTail {
			newPrefix += "    "
		} else {
			newPrefix += "│   "
		}
		outputByLibNum(node.Left, newPrefix, true, str)
	}
}

func (node *ByLibNumNode) grandparent() *ByLibNumNode {
	if node != nil && node.Parent != nil {
		return node.Parent.Parent
	}
	return nil
}

func (node *ByLibNumNode) uncle() *ByLibNumNode {
	if node == nil || node.Parent == nil || node.Parent.Parent == nil {
		return nil
	}
	return node.Parent.sibling()
}

func (node *ByLibNumNode) sibling() *ByLibNumNode {
	if node == nil || node.Parent == nil {
		return nil
	}
	if node == node.Parent.Left {
		return node.Parent.Right
	}
	return node.Parent.Left
}

func (node *ByLibNumNode) isLeaf() bool {
	if node == nil {
		return true
	}
	if node.Right == nil && node.Left == nil {
		return true
	}
	return false
}

func (tree *ByLibNum) rotateLeft(node *ByLibNumNode) {
	right := node.Right
	tree.replaceNode(node, right)
	node.Right = right.Left
	if right.Left != nil {
		right.Left.Parent = node
	}
	right.Left = node
	node.Parent = right
}

func (tree *ByLibNum) rotateRight(node *ByLibNumNode) {
	left := node.Left
	tree.replaceNode(node, left)
	node.Left = left.Right
	if left.Right != nil {
		left.Right.Parent = node
	}
	left.Right = node
	node.Parent = left
}

func (tree *ByLibNum) replaceNode(old *ByLibNumNode, new *ByLibNumNode) {
	if old.Parent == nil {
		tree.Root = new
	} else {
		if old == old.Parent.Left {
			old.Parent.Left = new
		} else {
			old.Parent.Right = new
		}
	}
	if new != nil {
		new.Parent = old.Parent
	}
}

func (tree *ByLibNum) insertCase1(node *ByLibNumNode) {
	if node.Parent == nil {
		node.color = blackByLibNum
	} else {
		tree.insertCase2(node)
	}
}

func (tree *ByLibNum) insertCase2(node *ByLibNumNode) {
	if nodeColorByLibNum(node.Parent) == blackByLibNum {
		return
	}
	tree.insertCase3(node)
}

func (tree *ByLibNum) insertCase3(node *ByLibNumNode) {
	uncle := node.uncle()
	if nodeColorByLibNum(uncle) == redByLibNum {
		node.Parent.color = blackByLibNum
		uncle.color = blackByLibNum
		node.grandparent().color = redByLibNum
		tree.insertCase1(node.grandparent())
	} else {
		tree.insertCase4(node)
	}
}

func (tree *ByLibNum) insertCase4(node *ByLibNumNode) {
	grandparent := node.grandparent()
	if node == node.Parent.Right && node.Parent == grandparent.Left {
		tree.rotateLeft(node.Parent)
		node = node.Left
	} else if node == node.Parent.Left && node.Parent == grandparent.Right {
		tree.rotateRight(node.Parent)
		node = node.Right
	}
	tree.insertCase5(node)
}

func (tree *ByLibNum) insertCase5(node *ByLibNumNode) {
	node.Parent.color = blackByLibNum
	grandparent := node.grandparent()
	grandparent.color = redByLibNum
	if node == node.Parent.Left && node.Parent == grandparent.Left {
		tree.rotateRight(grandparent)
	} else if node == node.Parent.Right && node.Parent == grandparent.Right {
		tree.rotateLeft(grandparent)
	}
}

func (node *ByLibNumNode) maximumNode() *ByLibNumNode {
	if node == nil {
		return nil
	}
	for node.Right != nil {
		node = node.Right
	}
	return node
}

func (tree *ByLibNum) deleteCase1(node *ByLibNumNode) {
	if node.Parent == nil {
		return
	}
	tree.deleteCase2(node)
}

func (tree *ByLibNum) deleteCase2(node *ByLibNumNode) {
	sibling := node.sibling()
	if nodeColorByLibNum(sibling) == redByLibNum {
		node.Parent.color = redByLibNum
		sibling.color = blackByLibNum
		if node == node.Parent.Left {
			tree.rotateLeft(node.Parent)
		} else {
			tree.rotateRight(node.Parent)
		}
	}
	tree.deleteCase3(node)
}

func (tree *ByLibNum) deleteCase3(node *ByLibNumNode) {
	sibling := node.sibling()
	if nodeColorByLibNum(node.Parent) == blackByLibNum &&
		nodeColorByLibNum(sibling) == blackByLibNum &&
		nodeColorByLibNum(sibling.Left) == blackByLibNum &&
		nodeColorByLibNum(sibling.Right) == blackByLibNum {
		sibling.color = redByLibNum
		tree.deleteCase1(node.Parent)
	} else {
		tree.deleteCase4(node)
	}
}

func (tree *ByLibNum) deleteCase4(node *ByLibNumNode) {
	sibling := node.sibling()
	if nodeColorByLibNum(node.Parent) == redByLibNum &&
		nodeColorByLibNum(sibling) == blackByLibNum &&
		nodeColorByLibNum(sibling.Left) == blackByLibNum &&
		nodeColorByLibNum(sibling.Right) == blackByLibNum {
		sibling.color = redByLibNum
		node.Parent.color = blackByLibNum
	} else {
		tree.deleteCase5(node)
	}
}

func (tree *ByLibNum) deleteCase5(node *ByLibNumNode) {
	sibling := node.sibling()
	if node == node.Parent.Left &&
		nodeColorByLibNum(sibling) == blackByLibNum &&
		nodeColorByLibNum(sibling.Left) == redByLibNum &&
		nodeColorByLibNum(sibling.Right) == blackByLibNum {
		sibling.color = redByLibNum
		sibling.Left.color = blackByLibNum
		tree.rotateRight(sibling)
	} else if node == node.Parent.Right &&
		nodeColorByLibNum(sibling) == blackByLibNum &&
		nodeColorByLibNum(sibling.Right) == redByLibNum &&
		nodeColorByLibNum(sibling.Left) == blackByLibNum {
		sibling.color = redByLibNum
		sibling.Right.color = blackByLibNum
		tree.rotateLeft(sibling)
	}
	tree.deleteCase6(node)
}

func (tree *ByLibNum) deleteCase6(node *ByLibNumNode) {
	sibling := node.sibling()
	sibling.color = nodeColorByLibNum(node.Parent)
	node.Parent.color = blackByLibNum
	if node == node.Parent.Left && nodeColorByLibNum(sibling.Right) == redByLibNum {
		sibling.Right.color = blackByLibNum
		tree.rotateLeft(node.Parent)
	} else if nodeColorByLibNum(sibling.Left) == redByLibNum {
		sibling.Left.color = blackByLibNum
		tree.rotateRight(node.Parent)
	}
}

func nodeColorByLibNum(node *ByLibNumNode) colorByLibNum {
	if node == nil {
		return blackByLibNum
	}
	return node.color
}

//////////////iterator////////////////

func (tree *ByLibNum) makeIterator(fn *TestIndexNode) IteratorByLibNum {
	node := fn.GetSuperNode()
	for {
		if node == nil {
			panic("Wrong index node type!")

		} else if n, ok := node.(*ByLibNumNode); ok {
			return IteratorByLibNum{tree: tree, node: n, position: betweenByLibNum}
		} else {
			node = node.(multiindex.NodeType).GetSuperNode()
		}
	}
}

// Iterator holding the iterator's state
type IteratorByLibNum struct {
	tree     *ByLibNum
	node     *ByLibNumNode
	position positionByLibNum
}

type positionByLibNum byte

const (
	beginByLibNum, betweenByLibNum, endByLibNum positionByLibNum = 0, 1, 2
)

// Iterator returns a stateful iterator whose elements are key/value pairs.
func (tree *ByLibNum) Iterator() IteratorByLibNum {
	return IteratorByLibNum{tree: tree, node: nil, position: beginByLibNum}
}

func (tree *ByLibNum) Begin() IteratorByLibNum {
	itr := IteratorByLibNum{tree: tree, node: nil, position: beginByLibNum}
	itr.Next()
	return itr
}

func (tree *ByLibNum) End() IteratorByLibNum {
	return IteratorByLibNum{tree: tree, node: nil, position: endByLibNum}
}

// Next moves the iterator to the next element and returns true if there was a next element in the container.
// If Next() returns true, then next element's key and value can be retrieved by Key() and Value().
// If Next() was called for the first time, then it will point the iterator to the first element if it exists.
// Modifies the state of the iterator.
func (iterator *IteratorByLibNum) Next() bool {
	if iterator.position == endByLibNum {
		goto end
	}
	if iterator.position == beginByLibNum {
		left := iterator.tree.Left()
		if left == nil {
			goto end
		}
		iterator.node = left
		goto between
	}
	if iterator.node.Right != nil {
		iterator.node = iterator.node.Right
		for iterator.node.Left != nil {
			iterator.node = iterator.node.Left
		}
		goto between
	}
	if iterator.node.Parent != nil {
		node := iterator.node
		for iterator.node.Parent != nil {
			iterator.node = iterator.node.Parent
			if node == iterator.node.Left {
				goto between
			}
			node = iterator.node
		}
	}

end:
	iterator.node = nil
	iterator.position = endByLibNum
	return false

between:
	iterator.position = betweenByLibNum
	return true
}

// Prev moves the iterator to the previous element and returns true if there was a previous element in the container.
// If Prev() returns true, then previous element's key and value can be retrieved by Key() and Value().
// Modifies the state of the iterator.
func (iterator *IteratorByLibNum) Prev() bool {
	if iterator.position == beginByLibNum {
		goto begin
	}
	if iterator.position == endByLibNum {
		right := iterator.tree.Right()
		if right == nil {
			goto begin
		}
		iterator.node = right
		goto between
	}
	if iterator.node.Left != nil {
		iterator.node = iterator.node.Left
		for iterator.node.Right != nil {
			iterator.node = iterator.node.Right
		}
		goto between
	}
	if iterator.node.Parent != nil {
		node := iterator.node
		for iterator.node.Parent != nil {
			iterator.node = iterator.node.Parent
			if node == iterator.node.Right {
				goto between
			}
			node = iterator.node
			//if iterator.tree.Comparator(node.Key, iterator.node.Key) >= 0 {
			//	goto between
			//}
		}
	}

begin:
	iterator.node = nil
	iterator.position = beginByLibNum
	return false

between:
	iterator.position = betweenByLibNum
	return true
}

func (iterator IteratorByLibNum) HasNext() bool {
	return iterator.position != endByLibNum
}

func (iterator *IteratorByLibNum) HasPrev() bool {
	return iterator.position != beginByLibNum
}

// Value returns the current element's value.
// Does not modify the state of the iterator.
func (iterator IteratorByLibNum) Value() ValueType {
	return *iterator.node.value()
}

// Key returns the current element's key.
// Does not modify the state of the iterator.
func (iterator IteratorByLibNum) Key() ByLibNumComposite {
	return iterator.node.Key
}

// Begin resets the iterator to its initial state (one-before-first)
// Call Next() to fetch the first element if any.
func (iterator *IteratorByLibNum) Begin() {
	iterator.node = nil
	iterator.position = beginByLibNum
}

func (iterator IteratorByLibNum) IsBegin() bool {
	return iterator.position == beginByLibNum
}

// End moves the iterator past the last element (one-past-the-end).
// Call Prev() to fetch the last element if any.
func (iterator *IteratorByLibNum) End() {
	iterator.node = nil
	iterator.position = endByLibNum
}

func (iterator IteratorByLibNum) IsEnd() bool {
	return iterator.position == endByLibNum
}

// Delete remove the node which pointed by the iterator
// Modifies the state of the iterator.
func (iterator *IteratorByLibNum) Delete() {
	node := iterator.node
	//iterator.Prev()
	iterator.tree.remove(node)
}

func (tree *ByLibNum) inPlace(n *ByLibNumNode) bool {
	prev := IteratorByLibNum{tree, n, betweenByLibNum}
	next := IteratorByLibNum{tree, n, betweenByLibNum}
	prev.Prev()
	next.Next()

	var (
		prevResult int
		nextResult int
	)

	if prev.IsBegin() {
		prevResult = 1
	} else {
		prevResult = ByLibNumCompare(n.Key, prev.Key())
	}

	if next.IsEnd() {
		nextResult = -1
	} else {
		nextResult = ByLibNumCompare(n.Key, next.Key())
	}

	return (true && prevResult >= 0 && nextResult <= 0) ||
		(!true && prevResult > 0 && nextResult < 0)
}
