// Code generated by gotemplate. DO NOT EDIT.

package mock_block

import (
	"fmt"

	"github.com/eosspark/eos-go/common/container"
	"github.com/eosspark/eos-go/common/container/multiindex"
)

// template type OrderedIndex(FinalIndex,FinalNode,SuperIndex,SuperNode,Value,Key,KeyFunc,Comparator,Multiply)

// OrderedIndex holds elements of the red-black tree
type ByPrev struct {
	super *ByNum     // index on the OrderedIndex, IndexBase is the last super index
	final *TestIndex // index under the OrderedIndex, MultiIndex is the final index

	Root *ByPrevNode
	size int
}

func (tree *ByPrev) init(final *TestIndex) {
	tree.final = final
	tree.super = &ByNum{}
	tree.super.init(final)
}

func (tree *ByPrev) clear() {
	tree.Clear()
	tree.super.clear()
}

/*generic class*/

/*generic class*/

// OrderedIndexNode is a single element within the tree
type ByPrevNode struct {
	Key    int
	super  *ByNumNode
	final  *TestIndexNode
	color  colorByPrev
	Left   *ByPrevNode
	Right  *ByPrevNode
	Parent *ByPrevNode
}

/*generic class*/

/*generic class*/

func (node *ByPrevNode) value() *ValueType {
	return node.super.value()
}

type colorByPrev bool

const (
	blackByPrev, redByPrev colorByPrev = true, false
)

func (tree *ByPrev) Insert(v ValueType) (IteratorByPrev, bool) {
	fn, res := tree.final.insert(v)
	if res {
		return tree.makeIterator(fn), true
	}
	return tree.End(), false
}

func (tree *ByPrev) insert(v ValueType, fn *TestIndexNode) (*ByPrevNode, bool) {
	key := ByPrevKeyFunc(v)

	node, res := tree.put(key)
	if !res {
		container.Logger.Warn("#ordered index insert failed")
		return nil, false
	}
	sn, res := tree.super.insert(v, fn)
	if res {
		node.super = sn
		node.final = fn
		return node, true
	}
	tree.remove(node)
	return nil, false
}

func (tree *ByPrev) Erase(iter IteratorByPrev) (itr IteratorByPrev) {
	itr = iter
	itr.Next()
	tree.final.erase(iter.node.final)
	return
}

func (tree *ByPrev) Erases(first, last IteratorByPrev) {
	for first != last {
		first = tree.Erase(first)
	}
}

func (tree *ByPrev) erase(n *ByPrevNode) {
	tree.remove(n)
	tree.super.erase(n.super)
	n.super = nil
	n.final = nil
}

func (tree *ByPrev) erase_(iter multiindex.IteratorType) {
	if itr, ok := iter.(IteratorByPrev); ok {
		tree.Erase(itr)
	} else {
		tree.super.erase_(iter)
	}
}

func (tree *ByPrev) Modify(iter IteratorByPrev, mod func(*ValueType)) bool {
	if _, b := tree.final.modify(mod, iter.node.final); b {
		return true
	}
	return false
}

func (tree *ByPrev) modify(n *ByPrevNode) (*ByPrevNode, bool) {
	n.Key = ByPrevKeyFunc(*n.value())

	if !tree.inPlace(n) {
		tree.remove(n)
		node, res := tree.put(n.Key)
		if !res {
			container.Logger.Warn("#ordered index modify failed")
			tree.super.erase(n.super)
			return nil, false
		}

		//n.Left = node.Left
		//if n.Left != nil {
		//	n.Left.Parent = n
		//}
		//n.Right = node.Right
		//if n.Right != nil {
		//	n.Right.Parent = n
		//}
		//n.Parent = node.Parent
		//if n.Parent != nil {
		//	if n.Parent.Left == node {
		//		n.Parent.Left = n
		//	} else {
		//		n.Parent.Right = n
		//	}
		//} else {
		//	tree.Root = n
		//}
		node.super = n.super
		node.final = n.final
		n = node
	}

	if sn, res := tree.super.modify(n.super); !res {
		tree.remove(n)
		return nil, false
	} else {
		n.super = sn
	}

	return n, true
}

func (tree *ByPrev) modify_(iter multiindex.IteratorType, mod func(*ValueType)) bool {
	if itr, ok := iter.(IteratorByPrev); ok {
		return tree.Modify(itr, mod)
	} else {
		return tree.super.modify_(iter, mod)
	}
}

// Get searches the node in the tree by key and returns its value or nil if key is not found in tree.
// Second return parameter is true if key was found, otherwise false.
// Key should adhere to the comparator's type assertion, otherwise method panics.
func (tree *ByPrev) Find(key int) IteratorByPrev {
	if true {
		lower := tree.LowerBound(key)
		if !lower.IsEnd() && ByPrevCompare(key, lower.Key()) == 0 {
			return lower
		}
		return tree.End()
	} else {
		if node := tree.lookup(key); node != nil {
			return IteratorByPrev{tree, node, betweenByPrev}
		}
		return tree.End()
	}
}

// LowerBound returns an iterator pointing to the first element that is not less than the given key.
// Complexity: O(log N).
func (tree *ByPrev) LowerBound(key int) IteratorByPrev {
	result := tree.End()
	node := tree.Root

	if node == nil {
		return result
	}

	for {
		if ByPrevCompare(key, node.Key) > 0 {
			if node.Right != nil {
				node = node.Right
			} else {
				return result
			}
		} else {
			result.node = node
			result.position = betweenByPrev
			if node.Left != nil {
				node = node.Left
			} else {
				return result
			}
		}
	}
}

// UpperBound returns an iterator pointing to the first element that is greater than the given key.
// Complexity: O(log N).
func (tree *ByPrev) UpperBound(key int) IteratorByPrev {
	result := tree.End()
	node := tree.Root

	if node == nil {
		return result
	}

	for {
		if ByPrevCompare(key, node.Key) >= 0 {
			if node.Right != nil {
				node = node.Right
			} else {
				return result
			}
		} else {
			result.node = node
			result.position = betweenByPrev
			if node.Left != nil {
				node = node.Left
			} else {
				return result
			}
		}
	}
}

// Remove remove the node from the tree by key.
// Key should adhere to the comparator's type assertion, otherwise method panics.
func (tree *ByPrev) Remove(key int) {
	if true {
		for lower := tree.LowerBound(key); lower.position != endByPrev; {
			if ByPrevCompare(lower.Key(), key) == 0 {
				node := lower.node
				lower.Next()
				tree.remove(node)
			} else {
				break
			}
		}
	} else {
		node := tree.lookup(key)
		tree.remove(node)
	}
}

func (tree *ByPrev) put(key int) (*ByPrevNode, bool) {
	var insertedNode *ByPrevNode
	if tree.Root == nil {
		// Assert key is of comparator's type for initial tree
		ByPrevCompare(key, key)
		tree.Root = &ByPrevNode{Key: key, color: redByPrev}
		insertedNode = tree.Root
	} else {
		node := tree.Root
		loop := true
		if true {
			for loop {
				compare := ByPrevCompare(key, node.Key)
				switch {
				case compare < 0:
					if node.Left == nil {
						node.Left = &ByPrevNode{Key: key, color: redByPrev}
						insertedNode = node.Left
						loop = false
					} else {
						node = node.Left
					}
				case compare >= 0:
					if node.Right == nil {
						node.Right = &ByPrevNode{Key: key, color: redByPrev}
						insertedNode = node.Right
						loop = false
					} else {
						node = node.Right
					}
				}
			}
		} else {
			for loop {
				compare := ByPrevCompare(key, node.Key)
				switch {
				case compare == 0:
					node.Key = key
					return node, false
				case compare < 0:
					if node.Left == nil {
						node.Left = &ByPrevNode{Key: key, color: redByPrev}
						insertedNode = node.Left
						loop = false
					} else {
						node = node.Left
					}
				case compare > 0:
					if node.Right == nil {
						node.Right = &ByPrevNode{Key: key, color: redByPrev}
						insertedNode = node.Right
						loop = false
					} else {
						node = node.Right
					}
				}
			}
		}
		insertedNode.Parent = node
	}
	tree.insertCase1(insertedNode)
	tree.size++

	return insertedNode, true
}

func (tree *ByPrev) swapNode(node *ByPrevNode, pred *ByPrevNode) {
	if node == pred {
		return
	}

	tmp := ByPrevNode{color: pred.color, Left: pred.Left, Right: pred.Right, Parent: pred.Parent}

	pred.color = node.color
	node.color = tmp.color

	pred.Right = node.Right
	if pred.Right != nil {
		pred.Right.Parent = pred
	}
	node.Right = tmp.Right
	if node.Right != nil {
		node.Right.Parent = node
	}

	if pred.Parent == node {
		pred.Left = node
		node.Left = tmp.Left
		if node.Left != nil {
			node.Left.Parent = node
		}

		pred.Parent = node.Parent
		if pred.Parent != nil {
			if pred.Parent.Left == node {
				pred.Parent.Left = pred
			} else {
				pred.Parent.Right = pred
			}
		} else {
			tree.Root = pred
		}
		node.Parent = pred

	} else {
		pred.Left = node.Left
		if pred.Left != nil {
			pred.Left.Parent = pred
		}
		node.Left = tmp.Left
		if node.Left != nil {
			node.Left.Parent = node
		}

		pred.Parent = node.Parent
		if pred.Parent != nil {
			if pred.Parent.Left == node {
				pred.Parent.Left = pred
			} else {
				pred.Parent.Right = pred
			}
		} else {
			tree.Root = pred
		}

		node.Parent = tmp.Parent
		if node.Parent != nil {
			if node.Parent.Left == pred {
				node.Parent.Left = node
			} else {
				node.Parent.Right = node
			}
		} else {
			tree.Root = node
		}
	}
}

func (tree *ByPrev) remove(node *ByPrevNode) {
	var child *ByPrevNode
	if node == nil {
		return
	}
	if node.Left != nil && node.Right != nil {
		pred := node.Left.maximumNode()
		tree.swapNode(node, pred)
	}
	if node.Left == nil || node.Right == nil {
		if node.Right == nil {
			child = node.Left
		} else {
			child = node.Right
		}
		if node.color == blackByPrev {
			node.color = nodeColorByPrev(child)
			tree.deleteCase1(node)
		}
		tree.replaceNode(node, child)
		if node.Parent == nil && child != nil {
			child.color = blackByPrev
		}
	}
	tree.size--
}

func (tree *ByPrev) lookup(key int) *ByPrevNode {
	node := tree.Root
	for node != nil {
		compare := ByPrevCompare(key, node.Key)
		switch {
		case compare == 0:
			return node
		case compare < 0:
			node = node.Left
		case compare > 0:
			node = node.Right
		}
	}
	return nil
}

// Empty returns true if tree does not contain any nodes
func (tree *ByPrev) Empty() bool {
	return tree.size == 0
}

// Size returns number of nodes in the tree.
func (tree *ByPrev) Size() int {
	return tree.size
}

// Keys returns all keys in-order
func (tree *ByPrev) Keys() []int {
	keys := make([]int, tree.size)
	it := tree.Iterator()
	for i := 0; it.Next(); i++ {
		keys[i] = it.Key()
	}
	return keys
}

// Values returns all values in-order based on the key.
func (tree *ByPrev) Values() []ValueType {
	values := make([]ValueType, tree.size)
	it := tree.Iterator()
	for i := 0; it.Next(); i++ {
		values[i] = it.Value()
	}
	return values
}

// Left returns the left-most (min) node or nil if tree is empty.
func (tree *ByPrev) Left() *ByPrevNode {
	var parent *ByPrevNode
	current := tree.Root
	for current != nil {
		parent = current
		current = current.Left
	}
	return parent
}

// Right returns the right-most (max) node or nil if tree is empty.
func (tree *ByPrev) Right() *ByPrevNode {
	var parent *ByPrevNode
	current := tree.Root
	for current != nil {
		parent = current
		current = current.Right
	}
	return parent
}

// Clear removes all nodes from the tree.
func (tree *ByPrev) Clear() {
	tree.Root = nil
	tree.size = 0
}

// String returns a string representation of container
func (tree *ByPrev) String() string {
	str := "OrderedIndex\n"
	if !tree.Empty() {
		outputByPrev(tree.Root, "", true, &str)
	}
	return str
}

func (node *ByPrevNode) String() string {
	if !node.color {
		return fmt.Sprintf("(%v,%v)", node.Key, "red")
	}
	return fmt.Sprintf("(%v)", node.Key)
}

func outputByPrev(node *ByPrevNode, prefix string, isTail bool, str *string) {
	if node.Right != nil {
		newPrefix := prefix
		if isTail {
			newPrefix += "│   "
		} else {
			newPrefix += "    "
		}
		outputByPrev(node.Right, newPrefix, false, str)
	}
	*str += prefix
	if isTail {
		*str += "└── "
	} else {
		*str += "┌── "
	}
	*str += node.String() + "\n"
	if node.Left != nil {
		newPrefix := prefix
		if isTail {
			newPrefix += "    "
		} else {
			newPrefix += "│   "
		}
		outputByPrev(node.Left, newPrefix, true, str)
	}
}

func (node *ByPrevNode) grandparent() *ByPrevNode {
	if node != nil && node.Parent != nil {
		return node.Parent.Parent
	}
	return nil
}

func (node *ByPrevNode) uncle() *ByPrevNode {
	if node == nil || node.Parent == nil || node.Parent.Parent == nil {
		return nil
	}
	return node.Parent.sibling()
}

func (node *ByPrevNode) sibling() *ByPrevNode {
	if node == nil || node.Parent == nil {
		return nil
	}
	if node == node.Parent.Left {
		return node.Parent.Right
	}
	return node.Parent.Left
}

func (node *ByPrevNode) isLeaf() bool {
	if node == nil {
		return true
	}
	if node.Right == nil && node.Left == nil {
		return true
	}
	return false
}

func (tree *ByPrev) rotateLeft(node *ByPrevNode) {
	right := node.Right
	tree.replaceNode(node, right)
	node.Right = right.Left
	if right.Left != nil {
		right.Left.Parent = node
	}
	right.Left = node
	node.Parent = right
}

func (tree *ByPrev) rotateRight(node *ByPrevNode) {
	left := node.Left
	tree.replaceNode(node, left)
	node.Left = left.Right
	if left.Right != nil {
		left.Right.Parent = node
	}
	left.Right = node
	node.Parent = left
}

func (tree *ByPrev) replaceNode(old *ByPrevNode, new *ByPrevNode) {
	if old.Parent == nil {
		tree.Root = new
	} else {
		if old == old.Parent.Left {
			old.Parent.Left = new
		} else {
			old.Parent.Right = new
		}
	}
	if new != nil {
		new.Parent = old.Parent
	}
}

func (tree *ByPrev) insertCase1(node *ByPrevNode) {
	if node.Parent == nil {
		node.color = blackByPrev
	} else {
		tree.insertCase2(node)
	}
}

func (tree *ByPrev) insertCase2(node *ByPrevNode) {
	if nodeColorByPrev(node.Parent) == blackByPrev {
		return
	}
	tree.insertCase3(node)
}

func (tree *ByPrev) insertCase3(node *ByPrevNode) {
	uncle := node.uncle()
	if nodeColorByPrev(uncle) == redByPrev {
		node.Parent.color = blackByPrev
		uncle.color = blackByPrev
		node.grandparent().color = redByPrev
		tree.insertCase1(node.grandparent())
	} else {
		tree.insertCase4(node)
	}
}

func (tree *ByPrev) insertCase4(node *ByPrevNode) {
	grandparent := node.grandparent()
	if node == node.Parent.Right && node.Parent == grandparent.Left {
		tree.rotateLeft(node.Parent)
		node = node.Left
	} else if node == node.Parent.Left && node.Parent == grandparent.Right {
		tree.rotateRight(node.Parent)
		node = node.Right
	}
	tree.insertCase5(node)
}

func (tree *ByPrev) insertCase5(node *ByPrevNode) {
	node.Parent.color = blackByPrev
	grandparent := node.grandparent()
	grandparent.color = redByPrev
	if node == node.Parent.Left && node.Parent == grandparent.Left {
		tree.rotateRight(grandparent)
	} else if node == node.Parent.Right && node.Parent == grandparent.Right {
		tree.rotateLeft(grandparent)
	}
}

func (node *ByPrevNode) maximumNode() *ByPrevNode {
	if node == nil {
		return nil
	}
	for node.Right != nil {
		node = node.Right
	}
	return node
}

func (tree *ByPrev) deleteCase1(node *ByPrevNode) {
	if node.Parent == nil {
		return
	}
	tree.deleteCase2(node)
}

func (tree *ByPrev) deleteCase2(node *ByPrevNode) {
	sibling := node.sibling()
	if nodeColorByPrev(sibling) == redByPrev {
		node.Parent.color = redByPrev
		sibling.color = blackByPrev
		if node == node.Parent.Left {
			tree.rotateLeft(node.Parent)
		} else {
			tree.rotateRight(node.Parent)
		}
	}
	tree.deleteCase3(node)
}

func (tree *ByPrev) deleteCase3(node *ByPrevNode) {
	sibling := node.sibling()
	if nodeColorByPrev(node.Parent) == blackByPrev &&
		nodeColorByPrev(sibling) == blackByPrev &&
		nodeColorByPrev(sibling.Left) == blackByPrev &&
		nodeColorByPrev(sibling.Right) == blackByPrev {
		sibling.color = redByPrev
		tree.deleteCase1(node.Parent)
	} else {
		tree.deleteCase4(node)
	}
}

func (tree *ByPrev) deleteCase4(node *ByPrevNode) {
	sibling := node.sibling()
	if nodeColorByPrev(node.Parent) == redByPrev &&
		nodeColorByPrev(sibling) == blackByPrev &&
		nodeColorByPrev(sibling.Left) == blackByPrev &&
		nodeColorByPrev(sibling.Right) == blackByPrev {
		sibling.color = redByPrev
		node.Parent.color = blackByPrev
	} else {
		tree.deleteCase5(node)
	}
}

func (tree *ByPrev) deleteCase5(node *ByPrevNode) {
	sibling := node.sibling()
	if node == node.Parent.Left &&
		nodeColorByPrev(sibling) == blackByPrev &&
		nodeColorByPrev(sibling.Left) == redByPrev &&
		nodeColorByPrev(sibling.Right) == blackByPrev {
		sibling.color = redByPrev
		sibling.Left.color = blackByPrev
		tree.rotateRight(sibling)
	} else if node == node.Parent.Right &&
		nodeColorByPrev(sibling) == blackByPrev &&
		nodeColorByPrev(sibling.Right) == redByPrev &&
		nodeColorByPrev(sibling.Left) == blackByPrev {
		sibling.color = redByPrev
		sibling.Right.color = blackByPrev
		tree.rotateLeft(sibling)
	}
	tree.deleteCase6(node)
}

func (tree *ByPrev) deleteCase6(node *ByPrevNode) {
	sibling := node.sibling()
	sibling.color = nodeColorByPrev(node.Parent)
	node.Parent.color = blackByPrev
	if node == node.Parent.Left && nodeColorByPrev(sibling.Right) == redByPrev {
		sibling.Right.color = blackByPrev
		tree.rotateLeft(node.Parent)
	} else if nodeColorByPrev(sibling.Left) == redByPrev {
		sibling.Left.color = blackByPrev
		tree.rotateRight(node.Parent)
	}
}

func nodeColorByPrev(node *ByPrevNode) colorByPrev {
	if node == nil {
		return blackByPrev
	}
	return node.color
}

//////////////iterator////////////////

func (tree *ByPrev) makeIterator(fn *TestIndexNode) IteratorByPrev {
	node := fn.GetSuperNode()
	for {
		if node == nil {
			panic("Wrong index node type!")

		} else if n, ok := node.(*ByPrevNode); ok {
			return IteratorByPrev{tree: tree, node: n, position: betweenByPrev}
		} else {
			node = node.(multiindex.NodeType).GetSuperNode()
		}
	}
}

// Iterator holding the iterator's state
type IteratorByPrev struct {
	tree     *ByPrev
	node     *ByPrevNode
	position positionByPrev
}

type positionByPrev byte

const (
	beginByPrev, betweenByPrev, endByPrev positionByPrev = 0, 1, 2
)

// Iterator returns a stateful iterator whose elements are key/value pairs.
func (tree *ByPrev) Iterator() IteratorByPrev {
	return IteratorByPrev{tree: tree, node: nil, position: beginByPrev}
}

func (tree *ByPrev) Begin() IteratorByPrev {
	itr := IteratorByPrev{tree: tree, node: nil, position: beginByPrev}
	itr.Next()
	return itr
}

func (tree *ByPrev) End() IteratorByPrev {
	return IteratorByPrev{tree: tree, node: nil, position: endByPrev}
}

// Next moves the iterator to the next element and returns true if there was a next element in the container.
// If Next() returns true, then next element's key and value can be retrieved by Key() and Value().
// If Next() was called for the first time, then it will point the iterator to the first element if it exists.
// Modifies the state of the iterator.
func (iterator *IteratorByPrev) Next() bool {
	if iterator.position == endByPrev {
		goto end
	}
	if iterator.position == beginByPrev {
		left := iterator.tree.Left()
		if left == nil {
			goto end
		}
		iterator.node = left
		goto between
	}
	if iterator.node.Right != nil {
		iterator.node = iterator.node.Right
		for iterator.node.Left != nil {
			iterator.node = iterator.node.Left
		}
		goto between
	}
	if iterator.node.Parent != nil {
		node := iterator.node
		for iterator.node.Parent != nil {
			iterator.node = iterator.node.Parent
			if node == iterator.node.Left {
				goto between
			}
			node = iterator.node
		}
	}

end:
	iterator.node = nil
	iterator.position = endByPrev
	return false

between:
	iterator.position = betweenByPrev
	return true
}

// Prev moves the iterator to the previous element and returns true if there was a previous element in the container.
// If Prev() returns true, then previous element's key and value can be retrieved by Key() and Value().
// Modifies the state of the iterator.
func (iterator *IteratorByPrev) Prev() bool {
	if iterator.position == beginByPrev {
		goto begin
	}
	if iterator.position == endByPrev {
		right := iterator.tree.Right()
		if right == nil {
			goto begin
		}
		iterator.node = right
		goto between
	}
	if iterator.node.Left != nil {
		iterator.node = iterator.node.Left
		for iterator.node.Right != nil {
			iterator.node = iterator.node.Right
		}
		goto between
	}
	if iterator.node.Parent != nil {
		node := iterator.node
		for iterator.node.Parent != nil {
			iterator.node = iterator.node.Parent
			if node == iterator.node.Right {
				goto between
			}
			node = iterator.node
			//if iterator.tree.Comparator(node.Key, iterator.node.Key) >= 0 {
			//	goto between
			//}
		}
	}

begin:
	iterator.node = nil
	iterator.position = beginByPrev
	return false

between:
	iterator.position = betweenByPrev
	return true
}

func (iterator IteratorByPrev) HasNext() bool {
	return iterator.position != endByPrev
}

func (iterator *IteratorByPrev) HasPrev() bool {
	return iterator.position != beginByPrev
}

// Value returns the current element's value.
// Does not modify the state of the iterator.
func (iterator IteratorByPrev) Value() ValueType {
	return *iterator.node.value()
}

// Key returns the current element's key.
// Does not modify the state of the iterator.
func (iterator IteratorByPrev) Key() int {
	return iterator.node.Key
}

// Begin resets the iterator to its initial state (one-before-first)
// Call Next() to fetch the first element if any.
func (iterator *IteratorByPrev) Begin() {
	iterator.node = nil
	iterator.position = beginByPrev
}

func (iterator IteratorByPrev) IsBegin() bool {
	return iterator.position == beginByPrev
}

// End moves the iterator past the last element (one-past-the-end).
// Call Prev() to fetch the last element if any.
func (iterator *IteratorByPrev) End() {
	iterator.node = nil
	iterator.position = endByPrev
}

func (iterator IteratorByPrev) IsEnd() bool {
	return iterator.position == endByPrev
}

// Delete remove the node which pointed by the iterator
// Modifies the state of the iterator.
func (iterator *IteratorByPrev) Delete() {
	node := iterator.node
	//iterator.Prev()
	iterator.tree.remove(node)
}

func (tree *ByPrev) inPlace(n *ByPrevNode) bool {
	prev := IteratorByPrev{tree, n, betweenByPrev}
	next := IteratorByPrev{tree, n, betweenByPrev}
	prev.Prev()
	next.Next()

	var (
		prevResult int
		nextResult int
	)

	if prev.IsBegin() {
		prevResult = 1
	} else {
		prevResult = ByPrevCompare(n.Key, prev.Key())
	}

	if next.IsEnd() {
		nextResult = -1
	} else {
		nextResult = ByPrevCompare(n.Key, next.Key())
	}

	return (true && prevResult >= 0 && nextResult <= 0) ||
		(!true && prevResult > 0 && nextResult < 0)
}
