// Code generated by gotemplate. DO NOT EDIT.

package node_transaction

import (
	"github.com/eosspark/eos-go/libraries/container"
	"github.com/eosspark/eos-go/libraries/multiindex"
	"github.com/eosspark/eos-go/plugins/net_plugin/multi_index"
)

// template type MultiIndex(SuperIndex,SuperNode,Value)

type NodeTransactionIndex struct {
	super *ById
	count int
}

func NewNodeTransactionIndex() *NodeTransactionIndex {
	m := &NodeTransactionIndex{}
	m.super = &ById{}
	m.super.init(m)
	return m
}

/*generic class*/

type NodeTransactionIndexNode struct {
	super *ByIdNode
}

/*generic class*/

//method for MultiIndex
func (m *NodeTransactionIndex) GetSuperIndex() interface{} { return m.super }
func (m *NodeTransactionIndex) GetFinalIndex() interface{} { return nil }

func (m *NodeTransactionIndex) GetIndex() interface{} {
	return nil
}

func (m *NodeTransactionIndex) Size() int {
	return m.count
}

func (m *NodeTransactionIndex) Clear() {
	m.super.clear()
	m.count = 0
}

func (m *NodeTransactionIndex) Insert(v multi_index.NodeTransactionState) bool {
	_, res := m.insert(v)
	return res
}

func (m *NodeTransactionIndex) insert(v multi_index.NodeTransactionState) (*NodeTransactionIndexNode, bool) {
	fn := &NodeTransactionIndexNode{}
	n, res := m.super.insert(v, fn)
	if res {
		fn.super = n
		m.count++
		return fn, true
	}
	return nil, false
}

func (m *NodeTransactionIndex) Erase(iter multiindex.IteratorType) {
	m.super.erase_(iter)
}

func (m *NodeTransactionIndex) erase(n *NodeTransactionIndexNode) {
	m.super.erase(n.super)
	m.count--
}

func (m *NodeTransactionIndex) Modify(iter multiindex.IteratorType, mod func(*multi_index.NodeTransactionState)) bool {
	return m.super.modify_(iter, mod)
}

func (m *NodeTransactionIndex) modify(mod func(*multi_index.NodeTransactionState), n *NodeTransactionIndexNode) (*NodeTransactionIndexNode, bool) {
	defer func() {
		if e := recover(); e != nil {
			container.Logger.Error("#multi modify failed: %v", e)
			m.erase(n)
			m.count--
			panic(e)
		}
	}()
	mod(n.value())
	if sn, res := m.super.modify(n.super); !res {
		m.count--
		return nil, false
	} else {
		n.super = sn
		return n, true
	}
}

func (n *NodeTransactionIndexNode) GetSuperNode() interface{} { return n.super }
func (n *NodeTransactionIndexNode) GetFinalNode() interface{} { return nil }

func (n *NodeTransactionIndexNode) value() *multi_index.NodeTransactionState {
	return n.super.value()
}

/// IndexBase
type NodeTransactionIndexBase struct {
	final *NodeTransactionIndex
}

type NodeTransactionIndexBaseNode struct {
	final *NodeTransactionIndexNode
	pv    *multi_index.NodeTransactionState
}

func (i *NodeTransactionIndexBase) init(final *NodeTransactionIndex) {
	i.final = final
}

func (i *NodeTransactionIndexBase) clear() {}

func (i *NodeTransactionIndexBase) GetSuperIndex() interface{} { return nil }

func (i *NodeTransactionIndexBase) GetFinalIndex() interface{} { return i.final }

func (i *NodeTransactionIndexBase) insert(v multi_index.NodeTransactionState, fn *NodeTransactionIndexNode) (*NodeTransactionIndexBaseNode, bool) {
	return &NodeTransactionIndexBaseNode{fn, &v}, true
}

func (i *NodeTransactionIndexBase) erase(n *NodeTransactionIndexBaseNode) {
	n.pv = nil
}

func (i *NodeTransactionIndexBase) erase_(iter multiindex.IteratorType) {
	container.Logger.Warn("erase iterator doesn't match all index")
}

func (i *NodeTransactionIndexBase) modify(n *NodeTransactionIndexBaseNode) (*NodeTransactionIndexBaseNode, bool) {
	return n, true
}

func (i *NodeTransactionIndexBase) modify_(iter multiindex.IteratorType, mod func(*multi_index.NodeTransactionState)) bool {
	container.Logger.Warn("modify iterator doesn't match all index")
	return false
}

func (n *NodeTransactionIndexBaseNode) value() *multi_index.NodeTransactionState {
	return n.pv
}
