// Code generated by gotemplate. DO NOT EDIT.

package forkdb_multi_index

import (
	"github.com/eosspark/eos-go/common/container/multiindex"
	"github.com/eosspark/eos-go/log"
)

// template type MultiIndex(SuperIndex,SuperNode,Value)

type MultiIndex struct {
	super *ByBlockId
	count int
}

func NewMultiIndex() *MultiIndex {
	m := &MultiIndex{}
	m.super = &ByBlockId{}
	m.super.init(m)
	return m
}

/*generic class*/

type MultiIndexNode struct {
	super *ByBlockIdNode
}

/*generic class*/

//method for MultiIndex
func (m *MultiIndex) GetSuperIndex() interface{} { return m.super }
func (m *MultiIndex) GetFinalIndex() interface{} { return nil }

func (m *MultiIndex) GetIndex() interface{} {
	return nil
}

func (m *MultiIndex) Size() int {
	return m.count
}

func (m *MultiIndex) Clear() {
	m.super.clear()
	m.count = 0
}

func (m *MultiIndex) Insert(v BlockStatePtr) bool {
	_, res := m.insert(v)
	return res
}

func (m *MultiIndex) insert(v BlockStatePtr) (*MultiIndexNode, bool) {
	fn := &MultiIndexNode{}
	n, res := m.super.insert(v, fn)
	if res {
		fn.super = n
		m.count++
		return fn, true
	}
	return nil, false
}

func (m *MultiIndex) Erase(iter multiindex.IteratorType) {
	m.super.erase_(iter)
}

func (m *MultiIndex) erase(n *MultiIndexNode) {
	m.super.erase(n.super)
	m.count--
}

func (m *MultiIndex) Modify(iter multiindex.IteratorType, mod func(*BlockStatePtr)) bool {
	return m.super.modify_(iter, mod)
}

func (m *MultiIndex) modify(mod func(*BlockStatePtr), n *MultiIndexNode) (*MultiIndexNode, bool) {
	defer func() {
		if e := recover(); e != nil {
			log.Error("#multi modify failed: %v", e)
			m.erase(n)
			m.count--
			panic(e)
		}
	}()
	mod(n.value())
	if sn, res := m.super.modify(n.super); !res {
		m.count--
		return nil, false
	} else {
		n.super = sn
		return n, true
	}
}

func (n *MultiIndexNode) GetSuperNode() interface{} { return n.super }
func (n *MultiIndexNode) GetFinalNode() interface{} { return nil }

func (n *MultiIndexNode) value() *BlockStatePtr {
	return n.super.value()
}

/// IndexBase
type MultiIndexBase struct {
	final *MultiIndex
}

type MultiIndexBaseNode struct {
	final *MultiIndexNode
	pv    *BlockStatePtr
}

func (i *MultiIndexBase) init(final *MultiIndex) {
	i.final = final
}

func (i *MultiIndexBase) clear() {}

func (i *MultiIndexBase) GetSuperIndex() interface{} { return nil }

func (i *MultiIndexBase) GetFinalIndex() interface{} { return i.final }

func (i *MultiIndexBase) insert(v BlockStatePtr, fn *MultiIndexNode) (*MultiIndexBaseNode, bool) {
	return &MultiIndexBaseNode{fn, &v}, true
}

func (i *MultiIndexBase) erase(n *MultiIndexBaseNode) {
	n.pv = nil
}

func (i *MultiIndexBase) erase_(iter multiindex.IteratorType) {
	log.Warn("erase iterator doesn't match all index")
}

func (i *MultiIndexBase) modify(n *MultiIndexBaseNode) (*MultiIndexBaseNode, bool) {
	return n, true
}

func (i *MultiIndexBase) modify_(iter multiindex.IteratorType, mod func(*BlockStatePtr)) bool {
	log.Warn("modify iterator doesn't match all index")
	return false
}

func (n *MultiIndexBaseNode) value() *BlockStatePtr {
	return n.pv
}
