package common

const (
	ChainUrl = "http://127.0.0.1:8888"
	// walletUrl = "http://127.0.0.1:8900"
	WalletUrl = "http://127.0.0.1:8888"
	// walletUrl = "http://127.0.0.1:8765"
	HttpEndPoint = "http://127.0.0.1:8888"
)

const (
	ChainFuncBase           string = "/v1/chain"
	GetInfoFunc             string = ChainFuncBase + "/get_info"
	PushTxnFunc             string = ChainFuncBase + "/push_transaction"
	PushTxnsFunc            string = ChainFuncBase + "/push_transactions"
	JsonToBinFunc           string = ChainFuncBase + "/abi_json_to_bin"
	GetBlockFunc            string = ChainFuncBase + "/get_block"
	GetBlockHeaderStateFunc string = ChainFuncBase + "/get_block_header_state"
	GetAccountFunc          string = ChainFuncBase + "/get_account"
	GetTableFunc            string = ChainFuncBase + "/get_table_rows"
	GetTableByScopeFunc     string = ChainFuncBase + "/get_table_by_scope"
	GetCodeFunc             string = ChainFuncBase + "/get_code"
	GetCodeHashFunc         string = ChainFuncBase + "/get_code_hash"
	GetAbiFunc              string = ChainFuncBase + "/get_abi"
	GetRawAbiFunc           string = ChainFuncBase + "/get_raw_abi"
	GetRawCodeAndAbiFunc    string = ChainFuncBase + "/get_raw_code_and_abi"
	GetCurrencyBalanceFunc  string = ChainFuncBase + "/get_currency_balance"
	GetCurrencyStatsFunc    string = ChainFuncBase + "/get_currency_stats"
	GetProducersFunc        string = ChainFuncBase + "/get_producers"
	GetScheduleFunc         string = ChainFuncBase + "/get_producer_schedule"
	GetRequiredKeys         string = ChainFuncBase + "/get_required_keys"

	HistoryFuncBase           string = "/v1/history"
	GetActionsFunc            string = HistoryFuncBase + "/get_actions"
	GetTransactionFunc        string = HistoryFuncBase + "/get_transaction"
	GetKeyAccountsFunc        string = HistoryFuncBase + "/get_key_accounts"
	GetControlledAccountsFunc string = HistoryFuncBase + "/get_controlled_accounts"

	AccountHistoryFuncBase string = "/v1/account_history"
	GetTransactionsFunc    string = AccountHistoryFuncBase + "/get_transactions"

	NetFuncBase    string = "/v1/net"
	NetConnect     string = NetFuncBase + "/connect"
	NetDisconnect  string = NetFuncBase + "/disconnect"
	NetStatus      string = NetFuncBase + "/status"
	NetConnections string = NetFuncBase + "/connections"

	WalletFuncBase   string = "/v1/wallet"
	WalletCreate     string = WalletFuncBase + "/create"
	WalletOpen       string = WalletFuncBase + "/open"
	WalletList       string = WalletFuncBase + "/list_wallets"
	WalletListKeys   string = WalletFuncBase + "/list_keys"
	WalletPublicKeys string = WalletFuncBase + "/get_public_keys"
	WalletLock       string = WalletFuncBase + "/lock"
	WalletLockAll    string = WalletFuncBase + "/lock_all"
	WalletUnlock     string = WalletFuncBase + "/unlock"
	WalletImportKey  string = WalletFuncBase + "/import_key"
	WalletRemoveKey  string = WalletFuncBase + "/remove_key"
	WalletCreateKey  string = WalletFuncBase + "/create_key"
	WalletSignTrx    string = WalletFuncBase + "/sign_transaction"

	// keosdStop string = "/v1/keosd/stop"

	ProducerFuncBase               string = "/v1/producer"
	ProducerPause                  string = ProducerFuncBase + "/pause"
	ProducerResume                 string = ProducerFuncBase + "/resume"
	ProducerPaused                 string = ProducerFuncBase + "/paused"
	ProducerGetRuntimeOptions      string = ProducerFuncBase + "/get_runtime_options"
	ProducerUpdateRuntimeOptions   string = ProducerFuncBase + "/update_runtime_options"
	ProducerAddGreylistAccounts    string = ProducerFuncBase + "/add_greylist_accounts"
	ProducerRemoveGreylistAccounts string = ProducerFuncBase + "/remove_greylist_accounts"
	ProducerGetGreylist            string = ProducerFuncBase + "/get_greylist"
	ProducerGetWhitelistBlacklist  string = ProducerFuncBase + "/get_whitelist_blacklist"
	ProducerSetWhitelistBlacklist  string = ProducerFuncBase + "/set_whitelist_blacklist"
	ProducerGetIntegrityHash       string = ProducerFuncBase + "/get_integrity_hash"
	ProducerCreateSnapshot         string = ProducerFuncBase + "/create_snapshot"
)
