// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TxDecompressionErrorName = reflect.TypeOf(TxDecompressionError{}).Name()

type TxDecompressionError struct {
	_TransactionException
	Elog log.Messages
}

func NewTxDecompressionError(parent _TransactionException, message log.Message) *TxDecompressionError {
	return &TxDecompressionError{parent, log.Messages{message}}
}

func (e TxDecompressionError) Code() int64 {
	return 3040001
}

func (e TxDecompressionError) Name() string {
	return TxDecompressionErrorName
}

func (e TxDecompressionError) What() string {
	return "Error decompressing transaction"
}

func (e *TxDecompressionError) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TxDecompressionError) GetLog() log.Messages {
	return e.Elog
}

func (e TxDecompressionError) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TxDecompressionError) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TxDecompressionError) String() string {
	return e.DetailMessage()
}

func (e TxDecompressionError) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040001,
		Name: TxDecompressionErrorName,
		What: "Error decompressing transaction",
	}

	return json.Marshal(except)
}

func (e TxDecompressionError) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TxDecompressionError):
		callback(&e)
		return true
	case func(TxDecompressionError):
		callback(e)
		return true
	default:
		return false
	}
}
