// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TxExpTooFarExceptionName = reflect.TypeOf(TxExpTooFarException{}).Name()

type TxExpTooFarException struct {
	_TransactionException
	Elog log.Messages
}

func NewTxExpTooFarException(parent _TransactionException, message log.Message) *TxExpTooFarException {
	return &TxExpTooFarException{parent, log.Messages{message}}
}

func (e TxExpTooFarException) Code() int64 {
	return 3040006
}

func (e TxExpTooFarException) Name() string {
	return TxExpTooFarExceptionName
}

func (e TxExpTooFarException) What() string {
	return "Transaction Expiration Too Far"
}

func (e *TxExpTooFarException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TxExpTooFarException) GetLog() log.Messages {
	return e.Elog
}

func (e TxExpTooFarException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TxExpTooFarException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TxExpTooFarException) String() string {
	return e.DetailMessage()
}

func (e TxExpTooFarException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040006,
		Name: TxExpTooFarExceptionName,
		What: "Transaction Expiration Too Far",
	}

	return json.Marshal(except)
}

func (e TxExpTooFarException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TxExpTooFarException):
		callback(&e)
		return true
	case func(TxExpTooFarException):
		callback(e)
		return true
	default:
		return false
	}
}
