// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TxDuplicateName = reflect.TypeOf(TxDuplicate{}).Name()

type TxDuplicate struct {
	_TransactionException
	Elog log.Messages
}

func NewTxDuplicate(parent _TransactionException, message log.Message) *TxDuplicate {
	return &TxDuplicate{parent, log.Messages{message}}
}

func (e TxDuplicate) Code() int64 {
	return 3040008
}

func (e TxDuplicate) Name() string {
	return TxDuplicateName
}

func (e TxDuplicate) What() string {
	return "Duplicate transaction"
}

func (e *TxDuplicate) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TxDuplicate) GetLog() log.Messages {
	return e.Elog
}

func (e TxDuplicate) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TxDuplicate) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TxDuplicate) String() string {
	return e.DetailMessage()
}

func (e TxDuplicate) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040008,
		Name: TxDuplicateName,
		What: "Duplicate transaction",
	}

	return json.Marshal(except)
}

func (e TxDuplicate) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TxDuplicate):
		callback(&e)
		return true
	case func(TxDuplicate):
		callback(e)
		return true
	default:
		return false
	}
}
