// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ActionNotFoundExceptionName = reflect.TypeOf(ActionNotFoundException{}).Name()

type ActionNotFoundException struct {
	_ActionValidateException
	Elog log.Messages
}

func NewActionNotFoundException(parent _ActionValidateException, message log.Message) *ActionNotFoundException {
	return &ActionNotFoundException{parent, log.Messages{message}}
}

func (e ActionNotFoundException) Code() int64 {
	return 3050005
}

func (e ActionNotFoundException) Name() string {
	return ActionNotFoundExceptionName
}

func (e ActionNotFoundException) What() string {
	return "Action can not be found"
}

func (e *ActionNotFoundException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ActionNotFoundException) GetLog() log.Messages {
	return e.Elog
}

func (e ActionNotFoundException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e ActionNotFoundException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e ActionNotFoundException) String() string {
	return e.DetailMessage()
}

func (e ActionNotFoundException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3050005,
		Name: ActionNotFoundExceptionName,
		What: "Action can not be found",
	}

	return json.Marshal(except)
}

func (e ActionNotFoundException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ActionNotFoundException):
		callback(&e)
		return true
	case func(ActionNotFoundException):
		callback(e)
		return true
	default:
		return false
	}
}
