// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var GuardExceptionName = reflect.TypeOf(GuardException{}).Name()

type GuardException struct {
	_GuardException
	Elog log.Messages
}

func NewGuardException(parent _GuardException, message log.Message) *GuardException {
	return &GuardException{parent, log.Messages{message}}
}

func (e GuardException) Code() int64 {
	return 3060100
}

func (e GuardException) Name() string {
	return GuardExceptionName
}

func (e GuardException) What() string {
	return "Database exception"
}

func (e *GuardException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e GuardException) GetLog() log.Messages {
	return e.Elog
}

func (e GuardException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e GuardException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e GuardException) String() string {
	return e.DetailMessage()
}

func (e GuardException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3060100,
		Name: GuardExceptionName,
		What: "Database exception",
	}

	return json.Marshal(except)
}

func (e GuardException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*GuardException):
		callback(&e)
		return true
	case func(GuardException):
		callback(e)
		return true
	default:
		return false
	}
}
