// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ActorBlacklistExceptionName = reflect.TypeOf(ActorBlacklistException{}).Name()

type ActorBlacklistException struct {
	_WhitelistBlacklistException
	Elog log.Messages
}

func NewActorBlacklistException(parent _WhitelistBlacklistException, message log.Message) *ActorBlacklistException {
	return &ActorBlacklistException{parent, log.Messages{message}}
}

func (e ActorBlacklistException) Code() int64 {
	return 3130002
}

func (e ActorBlacklistException) Name() string {
	return ActorBlacklistExceptionName
}

func (e ActorBlacklistException) What() string {
	return "Authorizing actor of transaction is on the blacklist"
}

func (e *ActorBlacklistException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ActorBlacklistException) GetLog() log.Messages {
	return e.Elog
}

func (e ActorBlacklistException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e ActorBlacklistException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e ActorBlacklistException) String() string {
	return e.DetailMessage()
}

func (e ActorBlacklistException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3130002,
		Name: ActorBlacklistExceptionName,
		What: "Authorizing actor of transaction is on the blacklist",
	}

	return json.Marshal(except)
}

func (e ActorBlacklistException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ActorBlacklistException):
		callback(&e)
		return true
	case func(ActorBlacklistException):
		callback(e)
		return true
	default:
		return false
	}
}
