// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var UnknownTransactionCompressionName = reflect.TypeOf(UnknownTransactionCompression{}).Name()

type UnknownTransactionCompression struct {
	_TransactionException
	Elog log.Messages
}

func NewUnknownTransactionCompression(parent _TransactionException, message log.Message) *UnknownTransactionCompression {
	return &UnknownTransactionCompression{parent, log.Messages{message}}
}

func (e UnknownTransactionCompression) Code() int64 {
	return 3040014
}

func (e UnknownTransactionCompression) Name() string {
	return UnknownTransactionCompressionName
}

func (e UnknownTransactionCompression) What() string {
	return "Unknown transaction compression"
}

func (e *UnknownTransactionCompression) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e UnknownTransactionCompression) GetLog() log.Messages {
	return e.Elog
}

func (e UnknownTransactionCompression) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e UnknownTransactionCompression) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e UnknownTransactionCompression) String() string {
	return e.DetailMessage()
}

func (e UnknownTransactionCompression) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040014,
		Name: UnknownTransactionCompressionName,
		What: "Unknown transaction compression",
	}

	return json.Marshal(except)
}

func (e UnknownTransactionCompression) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*UnknownTransactionCompression):
		callback(&e)
		return true
	case func(UnknownTransactionCompression):
		callback(e)
		return true
	default:
		return false
	}
}
