// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ForkDbBlockNotFoundName = reflect.TypeOf(ForkDbBlockNotFound{}).Name()

type ForkDbBlockNotFound struct {
	_ForkDatabaseException
	Elog log.Messages
}

func NewForkDbBlockNotFound(parent _ForkDatabaseException, message log.Message) *ForkDbBlockNotFound {
	return &ForkDbBlockNotFound{parent, log.Messages{message}}
}

func (e ForkDbBlockNotFound) Code() int64 {
	return 3020001
}

func (e ForkDbBlockNotFound) Name() string {
	return ForkDbBlockNotFoundName
}

func (e ForkDbBlockNotFound) What() string {
	return "Block can not be found"
}

func (e *ForkDbBlockNotFound) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ForkDbBlockNotFound) GetLog() log.Messages {
	return e.Elog
}

func (e ForkDbBlockNotFound) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e ForkDbBlockNotFound) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e ForkDbBlockNotFound) String() string {
	return e.DetailMessage()
}

func (e ForkDbBlockNotFound) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3020001,
		Name: ForkDbBlockNotFoundName,
		What: "Block can not be found",
	}

	return json.Marshal(except)
}

func (e ForkDbBlockNotFound) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ForkDbBlockNotFound):
		callback(&e)
		return true
	case func(ForkDbBlockNotFound):
		callback(e)
		return true
	default:
		return false
	}
}
