// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var BadCastExceptionName = reflect.TypeOf(BadCastException{}).Name()

type BadCastException struct {
	Exception
	Elog log.Messages
}

func NewBadCastException(parent Exception, message log.Message) *BadCastException {
	return &BadCastException{parent, log.Messages{message}}
}

func (e BadCastException) Code() int64 {
	return BadCastExceptionCode
}

func (e BadCastException) Name() string {
	return BadCastExceptionName
}

func (e BadCastException) What() string {
	return "Bad Cast"
}

func (e *BadCastException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e BadCastException) GetLog() log.Messages {
	return e.Elog
}

func (e BadCastException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e BadCastException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e BadCastException) String() string {
	return e.DetailMessage()
}

func (e BadCastException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: BadCastExceptionCode,
		Name: BadCastExceptionName,
		What: "Bad Cast",
	}

	return json.Marshal(except)
}

func (e BadCastException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*BadCastException):
		callback(&e)
		return true
	case func(BadCastException):
		callback(e)
		return true
	default:
		return false
	}
}
