// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var WalletNotAvailableExceptionName = reflect.TypeOf(WalletNotAvailableException{}).Name()

type WalletNotAvailableException struct {
	_WalletException
	Elog log.Messages
}

func NewWalletNotAvailableException(parent _WalletException, message log.Message) *WalletNotAvailableException {
	return &WalletNotAvailableException{parent, log.Messages{message}}
}

func (e WalletNotAvailableException) Code() int64 {
	return 3120006
}

func (e WalletNotAvailableException) Name() string {
	return WalletNotAvailableExceptionName
}

func (e WalletNotAvailableException) What() string {
	return "No available wallet"
}

func (e *WalletNotAvailableException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e WalletNotAvailableException) GetLog() log.Messages {
	return e.Elog
}

func (e WalletNotAvailableException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e WalletNotAvailableException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e WalletNotAvailableException) String() string {
	return e.DetailMessage()
}

func (e WalletNotAvailableException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3120006,
		Name: WalletNotAvailableExceptionName,
		What: "No available wallet",
	}

	return json.Marshal(except)
}

func (e WalletNotAvailableException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*WalletNotAvailableException):
		callback(&e)
		return true
	case func(WalletNotAvailableException):
		callback(e)
		return true
	default:
		return false
	}
}
