// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var UnsatisfiedAuthorizationName = reflect.TypeOf(UnsatisfiedAuthorization{}).Name()

type UnsatisfiedAuthorization struct {
	_AuthorizationException
	Elog log.Messages
}

func NewUnsatisfiedAuthorization(parent _AuthorizationException, message log.Message) *UnsatisfiedAuthorization {
	return &UnsatisfiedAuthorization{parent, log.Messages{message}}
}

func (e UnsatisfiedAuthorization) Code() int64 {
	return 3090003
}

func (e UnsatisfiedAuthorization) Name() string {
	return UnsatisfiedAuthorizationName
}

func (e UnsatisfiedAuthorization) What() string {
	return "Provided keys, permissions, and delays do not satisfy declared authorizations"
}

func (e *UnsatisfiedAuthorization) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e UnsatisfiedAuthorization) GetLog() log.Messages {
	return e.Elog
}

func (e UnsatisfiedAuthorization) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e UnsatisfiedAuthorization) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e UnsatisfiedAuthorization) String() string {
	return e.DetailMessage()
}

func (e UnsatisfiedAuthorization) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3090003,
		Name: UnsatisfiedAuthorizationName,
		What: "Provided keys, permissions, and delays do not satisfy declared authorizations",
	}

	return json.Marshal(except)
}

func (e UnsatisfiedAuthorization) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*UnsatisfiedAuthorization):
		callback(&e)
		return true
	case func(UnsatisfiedAuthorization):
		callback(e)
		return true
	default:
		return false
	}
}
