// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var WhitelistBlacklistExceptionName = reflect.TypeOf(WhitelistBlacklistException{}).Name()

type WhitelistBlacklistException struct {
	_WhitelistBlacklistException
	Elog log.Messages
}

func NewWhitelistBlacklistException(parent _WhitelistBlacklistException, message log.Message) *WhitelistBlacklistException {
	return &WhitelistBlacklistException{parent, log.Messages{message}}
}

func (e WhitelistBlacklistException) Code() int64 {
	return 3130000
}

func (e WhitelistBlacklistException) Name() string {
	return WhitelistBlacklistExceptionName
}

func (e WhitelistBlacklistException) What() string {
	return "Actor or contract whitelist/blacklist exception"
}

func (e *WhitelistBlacklistException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e WhitelistBlacklistException) GetLog() log.Messages {
	return e.Elog
}

func (e WhitelistBlacklistException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e WhitelistBlacklistException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e WhitelistBlacklistException) String() string {
	return e.DetailMessage()
}

func (e WhitelistBlacklistException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3130000,
		Name: WhitelistBlacklistExceptionName,
		What: "Actor or contract whitelist/blacklist exception",
	}

	return json.Marshal(except)
}

func (e WhitelistBlacklistException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*WhitelistBlacklistException):
		callback(&e)
		return true
	case func(WhitelistBlacklistException):
		callback(e)
		return true
	default:
		return false
	}
}
