// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var CfaIrrelevantAuthName = reflect.TypeOf(CfaIrrelevantAuth{}).Name()

type CfaIrrelevantAuth struct {
	_TransactionException
	Elog log.Messages
}

func NewCfaIrrelevantAuth(parent _TransactionException, message log.Message) *CfaIrrelevantAuth {
	return &CfaIrrelevantAuth{parent, log.Messages{message}}
}

func (e CfaIrrelevantAuth) Code() int64 {
	return 3040004
}

func (e CfaIrrelevantAuth) Name() string {
	return CfaIrrelevantAuthName
}

func (e CfaIrrelevantAuth) What() string {
	return "Context-free action should have no required authority"
}

func (e *CfaIrrelevantAuth) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e CfaIrrelevantAuth) GetLog() log.Messages {
	return e.Elog
}

func (e CfaIrrelevantAuth) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e CfaIrrelevantAuth) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e CfaIrrelevantAuth) String() string {
	return e.DetailMessage()
}

func (e CfaIrrelevantAuth) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040004,
		Name: CfaIrrelevantAuthName,
		What: "Context-free action should have no required authority",
	}

	return json.Marshal(except)
}

func (e CfaIrrelevantAuth) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*CfaIrrelevantAuth):
		callback(&e)
		return true
	case func(CfaIrrelevantAuth):
		callback(e)
		return true
	default:
		return false
	}
}
