// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var BlockLogNotFoundName = reflect.TypeOf(BlockLogNotFound{}).Name()

type BlockLogNotFound struct {
	_BlockLogException
	Elog log.Messages
}

func NewBlockLogNotFound(parent _BlockLogException, message log.Message) *BlockLogNotFound {
	return &BlockLogNotFound{parent, log.Messages{message}}
}

func (e BlockLogNotFound) Code() int64 {
	return 3190003
}

func (e BlockLogNotFound) Name() string {
	return BlockLogNotFoundName
}

func (e BlockLogNotFound) What() string {
	return "block log can not be found"
}

func (e *BlockLogNotFound) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e BlockLogNotFound) GetLog() log.Messages {
	return e.Elog
}

func (e BlockLogNotFound) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e BlockLogNotFound) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e BlockLogNotFound) String() string {
	return e.DetailMessage()
}

func (e BlockLogNotFound) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3190003,
		Name: BlockLogNotFoundName,
		What: "block log can not be found",
	}

	return json.Marshal(except)
}

func (e BlockLogNotFound) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*BlockLogNotFound):
		callback(&e)
		return true
	case func(BlockLogNotFound):
		callback(e)
		return true
	default:
		return false
	}
}
