// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var PluginConfigExceptionName = reflect.TypeOf(PluginConfigException{}).Name()

type PluginConfigException struct {
	_PluginException
	Elog log.Messages
}

func NewPluginConfigException(parent _PluginException, message log.Message) *PluginConfigException {
	return &PluginConfigException{parent, log.Messages{message}}
}

func (e PluginConfigException) Code() int64 {
	return 3110006
}

func (e PluginConfigException) Name() string {
	return PluginConfigExceptionName
}

func (e PluginConfigException) What() string {
	return "Incorrect plugin configuration"
}

func (e *PluginConfigException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e PluginConfigException) GetLog() log.Messages {
	return e.Elog
}

func (e PluginConfigException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e PluginConfigException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e PluginConfigException) String() string {
	return e.DetailMessage()
}

func (e PluginConfigException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3110006,
		Name: PluginConfigExceptionName,
		What: "Incorrect plugin configuration",
	}

	return json.Marshal(except)
}

func (e PluginConfigException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*PluginConfigException):
		callback(&e)
		return true
	case func(PluginConfigException):
		callback(e)
		return true
	default:
		return false
	}
}
