// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TxTooBigName = reflect.TypeOf(TxTooBig{}).Name()

type TxTooBig struct {
	_TransactionException
	Elog log.Messages
}

func NewTxTooBig(parent _TransactionException, message log.Message) *TxTooBig {
	return &TxTooBig{parent, log.Messages{message}}
}

func (e TxTooBig) Code() int64 {
	return 3040013
}

func (e TxTooBig) Name() string {
	return TxTooBigName
}

func (e TxTooBig) What() string {
	return "Transaction is too big"
}

func (e *TxTooBig) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TxTooBig) GetLog() log.Messages {
	return e.Elog
}

func (e TxTooBig) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TxTooBig) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TxTooBig) String() string {
	return e.DetailMessage()
}

func (e TxTooBig) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040013,
		Name: TxTooBigName,
		What: "Transaction is too big",
	}

	return json.Marshal(except)
}

func (e TxTooBig) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TxTooBig):
		callback(&e)
		return true
	case func(TxTooBig):
		callback(e)
		return true
	default:
		return false
	}
}
