// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AbortCalledName = reflect.TypeOf(AbortCalled{}).Name()

type AbortCalled struct {
	_ActionValidateException
	Elog log.Messages
}

func NewAbortCalled(parent _ActionValidateException, message log.Message) *AbortCalled {
	return &AbortCalled{parent, log.Messages{message}}
}

func (e AbortCalled) Code() int64 {
	return 3050008
}

func (e AbortCalled) Name() string {
	return AbortCalledName
}

func (e AbortCalled) What() string {
	return "Abort Calle"
}

func (e *AbortCalled) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AbortCalled) GetLog() log.Messages {
	return e.Elog
}

func (e AbortCalled) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e AbortCalled) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e AbortCalled) String() string {
	return e.DetailMessage()
}

func (e AbortCalled) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3050008,
		Name: AbortCalledName,
		What: "Abort Calle",
	}

	return json.Marshal(except)
}

func (e AbortCalled) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AbortCalled):
		callback(&e)
		return true
	case func(AbortCalled):
		callback(e)
		return true
	default:
		return false
	}
}
