// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TableNotInCacheName = reflect.TypeOf(TableNotInCache{}).Name()

type TableNotInCache struct {
	_ContractException
	Elog log.Messages
}

func NewTableNotInCache(parent _ContractException, message log.Message) *TableNotInCache {
	return &TableNotInCache{parent, log.Messages{message}}
}

func (e TableNotInCache) Code() int64 {
	return 3160004
}

func (e TableNotInCache) Name() string {
	return TableNotInCacheName
}

func (e TableNotInCache) What() string {
	return "Table can not be found inside the cache"
}

func (e *TableNotInCache) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TableNotInCache) GetLog() log.Messages {
	return e.Elog
}

func (e TableNotInCache) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TableNotInCache) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TableNotInCache) String() string {
	return e.DetailMessage()
}

func (e TableNotInCache) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3160004,
		Name: TableNotInCacheName,
		What: "Table can not be found inside the cache",
	}

	return json.Marshal(except)
}

func (e TableNotInCache) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TableNotInCache):
		callback(&e)
		return true
	case func(TableNotInCache):
		callback(e)
		return true
	default:
		return false
	}
}
