// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var LocalizedExceptionName = reflect.TypeOf(LocalizedException{}).Name()

type LocalizedException struct {
	Exception
	Elog log.Messages
}

func NewLocalizedException(parent Exception, message log.Message) *LocalizedException {
	return &LocalizedException{parent, log.Messages{message}}
}

func (e LocalizedException) Code() int64 {
	return 10000000
}

func (e LocalizedException) Name() string {
	return LocalizedExceptionName
}

func (e LocalizedException) What() string {
	return "an error occurred"
}

func (e *LocalizedException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e LocalizedException) GetLog() log.Messages {
	return e.Elog
}

func (e LocalizedException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e LocalizedException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e LocalizedException) String() string {
	return e.DetailMessage()
}

func (e LocalizedException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 10000000,
		Name: LocalizedExceptionName,
		What: "an error occurred",
	}

	return json.Marshal(except)
}

func (e LocalizedException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*LocalizedException):
		callback(&e)
		return true
	case func(LocalizedException):
		callback(e)
		return true
	default:
		return false
	}
}
