// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ReversibleBlocksBackupDirExistName = reflect.TypeOf(ReversibleBlocksBackupDirExist{}).Name()

type ReversibleBlocksBackupDirExist struct {
	_ReversibleBlocksException
	Elog log.Messages
}

func NewReversibleBlocksBackupDirExist(parent _ReversibleBlocksException, message log.Message) *ReversibleBlocksBackupDirExist {
	return &ReversibleBlocksBackupDirExist{parent, log.Messages{message}}
}

func (e ReversibleBlocksBackupDirExist) Code() int64 {
	return 3180002
}

func (e ReversibleBlocksBackupDirExist) Name() string {
	return ReversibleBlocksBackupDirExistName
}

func (e ReversibleBlocksBackupDirExist) What() string {
	return "Backup directory for reversible blocks already exist"
}

func (e *ReversibleBlocksBackupDirExist) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ReversibleBlocksBackupDirExist) GetLog() log.Messages {
	return e.Elog
}

func (e ReversibleBlocksBackupDirExist) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e ReversibleBlocksBackupDirExist) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e ReversibleBlocksBackupDirExist) String() string {
	return e.DetailMessage()
}

func (e ReversibleBlocksBackupDirExist) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3180002,
		Name: ReversibleBlocksBackupDirExistName,
		What: "Backup directory for reversible blocks already exist",
	}

	return json.Marshal(except)
}

func (e ReversibleBlocksBackupDirExist) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ReversibleBlocksBackupDirExist):
		callback(&e)
		return true
	case func(ReversibleBlocksBackupDirExist):
		callback(e)
		return true
	default:
		return false
	}
}
