// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var DuplicateAbiActionDefExceptionName = reflect.TypeOf(DuplicateAbiActionDefException{}).Name()

type DuplicateAbiActionDefException struct {
	_AbiException
	Elog log.Messages
}

func NewDuplicateAbiActionDefException(parent _AbiException, message log.Message) *DuplicateAbiActionDefException {
	return &DuplicateAbiActionDefException{parent, log.Messages{message}}
}

func (e DuplicateAbiActionDefException) Code() int64 {
	return 3150007
}

func (e DuplicateAbiActionDefException) Name() string {
	return DuplicateAbiActionDefExceptionName
}

func (e DuplicateAbiActionDefException) What() string {
	return "Duplicate action definition in the ABI"
}

func (e *DuplicateAbiActionDefException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e DuplicateAbiActionDefException) GetLog() log.Messages {
	return e.Elog
}

func (e DuplicateAbiActionDefException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e DuplicateAbiActionDefException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e DuplicateAbiActionDefException) String() string {
	return e.DetailMessage()
}

func (e DuplicateAbiActionDefException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3150007,
		Name: DuplicateAbiActionDefExceptionName,
		What: "Duplicate action definition in the ABI",
	}

	return json.Marshal(except)
}

func (e DuplicateAbiActionDefException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*DuplicateAbiActionDefException):
		callback(&e)
		return true
	case func(DuplicateAbiActionDefException):
		callback(e)
		return true
	default:
		return false
	}
}
