// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TableOperationNotPermittedName = reflect.TypeOf(TableOperationNotPermitted{}).Name()

type TableOperationNotPermitted struct {
	_ContractException
	Elog log.Messages
}

func NewTableOperationNotPermitted(parent _ContractException, message log.Message) *TableOperationNotPermitted {
	return &TableOperationNotPermitted{parent, log.Messages{message}}
}

func (e TableOperationNotPermitted) Code() int64 {
	return 3160005
}

func (e TableOperationNotPermitted) Name() string {
	return TableOperationNotPermittedName
}

func (e TableOperationNotPermitted) What() string {
	return "The table operation is not allowed"
}

func (e *TableOperationNotPermitted) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TableOperationNotPermitted) GetLog() log.Messages {
	return e.Elog
}

func (e TableOperationNotPermitted) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TableOperationNotPermitted) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TableOperationNotPermitted) String() string {
	return e.DetailMessage()
}

func (e TableOperationNotPermitted) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3160005,
		Name: TableOperationNotPermittedName,
		What: "The table operation is not allowed",
	}

	return json.Marshal(except)
}

func (e TableOperationNotPermitted) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TableOperationNotPermitted):
		callback(&e)
		return true
	case func(TableOperationNotPermitted):
		callback(e)
		return true
	default:
		return false
	}
}
