// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var InvalidHttpClientRootCertName = reflect.TypeOf(InvalidHttpClientRootCert{}).Name()

type InvalidHttpClientRootCert struct {
	_HttpException
	Elog log.Messages
}

func NewInvalidHttpClientRootCert(parent _HttpException, message log.Message) *InvalidHttpClientRootCert {
	return &InvalidHttpClientRootCert{parent, log.Messages{message}}
}

func (e InvalidHttpClientRootCert) Code() int64 {
	return 3200001
}

func (e InvalidHttpClientRootCert) Name() string {
	return InvalidHttpClientRootCertName
}

func (e InvalidHttpClientRootCert) What() string {
	return "invalid http client root certificate"
}

func (e *InvalidHttpClientRootCert) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e InvalidHttpClientRootCert) GetLog() log.Messages {
	return e.Elog
}

func (e InvalidHttpClientRootCert) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e InvalidHttpClientRootCert) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e InvalidHttpClientRootCert) String() string {
	return e.DetailMessage()
}

func (e InvalidHttpClientRootCert) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3200001,
		Name: InvalidHttpClientRootCertName,
		What: "invalid http client root certificate",
	}

	return json.Marshal(except)
}

func (e InvalidHttpClientRootCert) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*InvalidHttpClientRootCert):
		callback(&e)
		return true
	case func(InvalidHttpClientRootCert):
		callback(e)
		return true
	default:
		return false
	}
}
