// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var BlockLockExceptionName = reflect.TypeOf(BlockLockException{}).Name()

type BlockLockException struct {
	_BlockValidateException
	Elog log.Messages
}

func NewBlockLockException(parent _BlockValidateException, message log.Message) *BlockLockException {
	return &BlockLockException{parent, log.Messages{message}}
}

func (e BlockLockException) Code() int64 {
	return 3030004
}

func (e BlockLockException) Name() string {
	return BlockLockExceptionName
}

func (e BlockLockException) What() string {
	return "Shard locks in block are incorrect or mal-formed"
}

func (e *BlockLockException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e BlockLockException) GetLog() log.Messages {
	return e.Elog
}

func (e BlockLockException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e BlockLockException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e BlockLockException) String() string {
	return e.DetailMessage()
}

func (e BlockLockException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3030004,
		Name: BlockLockExceptionName,
		What: "Shard locks in block are incorrect or mal-formed",
	}

	return json.Marshal(except)
}

func (e BlockLockException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*BlockLockException):
		callback(&e)
		return true
	case func(BlockLockException):
		callback(e)
		return true
	default:
		return false
	}
}
