// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ContractWhitelistExceptionName = reflect.TypeOf(ContractWhitelistException{}).Name()

type ContractWhitelistException struct {
	_WhitelistBlacklistException
	Elog log.Messages
}

func NewContractWhitelistException(parent _WhitelistBlacklistException, message log.Message) *ContractWhitelistException {
	return &ContractWhitelistException{parent, log.Messages{message}}
}

func (e ContractWhitelistException) Code() int64 {
	return 3130003
}

func (e ContractWhitelistException) Name() string {
	return ContractWhitelistExceptionName
}

func (e ContractWhitelistException) What() string {
	return "Contract to execute is not on the whitelist"
}

func (e *ContractWhitelistException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ContractWhitelistException) GetLog() log.Messages {
	return e.Elog
}

func (e ContractWhitelistException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e ContractWhitelistException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e ContractWhitelistException) String() string {
	return e.DetailMessage()
}

func (e ContractWhitelistException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3130003,
		Name: ContractWhitelistExceptionName,
		What: "Contract to execute is not on the whitelist",
	}

	return json.Marshal(except)
}

func (e ContractWhitelistException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ContractWhitelistException):
		callback(&e)
		return true
	case func(ContractWhitelistException):
		callback(e)
		return true
	default:
		return false
	}
}
