// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TransactionExceptionName = reflect.TypeOf(TransactionException{}).Name()

type TransactionException struct {
	_TransactionException
	Elog log.Messages
}

func NewTransactionException(parent _TransactionException, message log.Message) *TransactionException {
	return &TransactionException{parent, log.Messages{message}}
}

func (e TransactionException) Code() int64 {
	return 3040000
}

func (e TransactionException) Name() string {
	return TransactionExceptionName
}

func (e TransactionException) What() string {
	return "Transaction exception"
}

func (e *TransactionException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TransactionException) GetLog() log.Messages {
	return e.Elog
}

func (e TransactionException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e TransactionException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e TransactionException) String() string {
	return e.DetailMessage()
}

func (e TransactionException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040000,
		Name: TransactionExceptionName,
		What: "Transaction exception",
	}

	return json.Marshal(except)
}

func (e TransactionException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TransactionException):
		callback(&e)
		return true
	case func(TransactionException):
		callback(e)
		return true
	default:
		return false
	}
}
