// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var DuplicateAbiTableDefExceptionName = reflect.TypeOf(DuplicateAbiTableDefException{}).Name()

type DuplicateAbiTableDefException struct {
	_AbiException
	Elog log.Messages
}

func NewDuplicateAbiTableDefException(parent _AbiException, message log.Message) *DuplicateAbiTableDefException {
	return &DuplicateAbiTableDefException{parent, log.Messages{message}}
}

func (e DuplicateAbiTableDefException) Code() int64 {
	return 3150008
}

func (e DuplicateAbiTableDefException) Name() string {
	return DuplicateAbiTableDefExceptionName
}

func (e DuplicateAbiTableDefException) What() string {
	return "Duplicate table definition in the ABI"
}

func (e *DuplicateAbiTableDefException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e DuplicateAbiTableDefException) GetLog() log.Messages {
	return e.Elog
}

func (e DuplicateAbiTableDefException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e DuplicateAbiTableDefException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e DuplicateAbiTableDefException) String() string {
	return e.DetailMessage()
}

func (e DuplicateAbiTableDefException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3150008,
		Name: DuplicateAbiTableDefExceptionName,
		What: "Duplicate table definition in the ABI",
	}

	return json.Marshal(except)
}

func (e DuplicateAbiTableDefException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*DuplicateAbiTableDefException):
		callback(&e)
		return true
	case func(DuplicateAbiTableDefException):
		callback(e)
		return true
	default:
		return false
	}
}
