// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var BlockLogUnsupportedVersionName = reflect.TypeOf(BlockLogUnsupportedVersion{}).Name()

type BlockLogUnsupportedVersion struct {
	_BlockLogException
	Elog log.Messages
}

func NewBlockLogUnsupportedVersion(parent _BlockLogException, message log.Message) *BlockLogUnsupportedVersion {
	return &BlockLogUnsupportedVersion{parent, log.Messages{message}}
}

func (e BlockLogUnsupportedVersion) Code() int64 {
	return 3190001
}

func (e BlockLogUnsupportedVersion) Name() string {
	return BlockLogUnsupportedVersionName
}

func (e BlockLogUnsupportedVersion) What() string {
	return "unsupported version of block log"
}

func (e *BlockLogUnsupportedVersion) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e BlockLogUnsupportedVersion) GetLog() log.Messages {
	return e.Elog
}

func (e BlockLogUnsupportedVersion) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e BlockLogUnsupportedVersion) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e BlockLogUnsupportedVersion) String() string {
	return e.DetailMessage()
}

func (e BlockLogUnsupportedVersion) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3190001,
		Name: BlockLogUnsupportedVersionName,
		What: "unsupported version of block log",
	}

	return json.Marshal(except)
}

func (e BlockLogUnsupportedVersion) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*BlockLogUnsupportedVersion):
		callback(&e)
		return true
	case func(BlockLogUnsupportedVersion):
		callback(e)
		return true
	default:
		return false
	}
}
