// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AuthorityTypeExceptionName = reflect.TypeOf(AuthorityTypeException{}).Name()

type AuthorityTypeException struct {
	_ChainException
	Elog log.Messages
}

func NewAuthorityTypeException(parent _ChainException, message log.Message) *AuthorityTypeException {
	return &AuthorityTypeException{parent, log.Messages{message}}
}

func (e AuthorityTypeException) Code() int64 {
	return 3010004
}

func (e AuthorityTypeException) Name() string {
	return AuthorityTypeExceptionName
}

func (e AuthorityTypeException) What() string {
	return "Invalid authority"
}

func (e *AuthorityTypeException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AuthorityTypeException) GetLog() log.Messages {
	return e.Elog
}

func (e AuthorityTypeException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e AuthorityTypeException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e AuthorityTypeException) String() string {
	return e.DetailMessage()
}

func (e AuthorityTypeException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3010004,
		Name: AuthorityTypeExceptionName,
		What: "Invalid authority",
	}

	return json.Marshal(except)
}

func (e AuthorityTypeException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AuthorityTypeException):
		callback(&e)
		return true
	case func(AuthorityTypeException):
		callback(e)
		return true
	default:
		return false
	}
}
