// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var UnderflowExceptionName = reflect.TypeOf(UnderflowException{}).Name()

type UnderflowException struct {
	Exception
	Elog log.Messages
}

func NewUnderflowException(parent Exception, message log.Message) *UnderflowException {
	return &UnderflowException{parent, log.Messages{message}}
}

func (e UnderflowException) Code() int64 {
	return UnderflowCode
}

func (e UnderflowException) Name() string {
	return UnderflowExceptionName
}

func (e UnderflowException) What() string {
	return "Integer Underflow"
}

func (e *UnderflowException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e UnderflowException) GetLog() log.Messages {
	return e.Elog
}

func (e UnderflowException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e UnderflowException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e UnderflowException) String() string {
	return e.DetailMessage()
}

func (e UnderflowException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: UnderflowCode,
		Name: UnderflowExceptionName,
		What: "Integer Underflow",
	}

	return json.Marshal(except)
}

func (e UnderflowException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*UnderflowException):
		callback(&e)
		return true
	case func(UnderflowException):
		callback(e)
		return true
	default:
		return false
	}
}
