// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ExpiredTxExceptionName = reflect.TypeOf(ExpiredTxException{}).Name()

type ExpiredTxException struct {
	_TransactionException
	Elog log.Messages
}

func NewExpiredTxException(parent _TransactionException, message log.Message) *ExpiredTxException {
	return &ExpiredTxException{parent, log.Messages{message}}
}

func (e ExpiredTxException) Code() int64 {
	return 3040005
}

func (e ExpiredTxException) Name() string {
	return ExpiredTxExceptionName
}

func (e ExpiredTxException) What() string {
	return "Expired Transaction"
}

func (e *ExpiredTxException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ExpiredTxException) GetLog() log.Messages {
	return e.Elog
}

func (e ExpiredTxException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e ExpiredTxException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e ExpiredTxException) String() string {
	return e.DetailMessage()
}

func (e ExpiredTxException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040005,
		Name: ExpiredTxExceptionName,
		What: "Expired Transaction",
	}

	return json.Marshal(except)
}

func (e ExpiredTxException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ExpiredTxException):
		callback(&e)
		return true
	case func(ExpiredTxException):
		callback(e)
		return true
	default:
		return false
	}
}
