// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var WalletMissingPubKeyExceptionName = reflect.TypeOf(WalletMissingPubKeyException{}).Name()

type WalletMissingPubKeyException struct {
	_WalletException
	Elog log.Messages
}

func NewWalletMissingPubKeyException(parent _WalletException, message log.Message) *WalletMissingPubKeyException {
	return &WalletMissingPubKeyException{parent, log.Messages{message}}
}

func (e WalletMissingPubKeyException) Code() int64 {
	return 3120004
}

func (e WalletMissingPubKeyException) Name() string {
	return WalletMissingPubKeyExceptionName
}

func (e WalletMissingPubKeyException) What() string {
	return "Missing public key"
}

func (e *WalletMissingPubKeyException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e WalletMissingPubKeyException) GetLog() log.Messages {
	return e.Elog
}

func (e WalletMissingPubKeyException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e WalletMissingPubKeyException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e WalletMissingPubKeyException) String() string {
	return e.DetailMessage()
}

func (e WalletMissingPubKeyException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3120004,
		Name: WalletMissingPubKeyExceptionName,
		What: "Missing public key",
	}

	return json.Marshal(except)
}

func (e WalletMissingPubKeyException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*WalletMissingPubKeyException):
		callback(&e)
		return true
	case func(WalletMissingPubKeyException):
		callback(e)
		return true
	default:
		return false
	}
}
