// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AbiFileNotFoundName = reflect.TypeOf(AbiFileNotFound{}).Name()

type AbiFileNotFound struct {
	_ContractException
	Elog log.Messages
}

func NewAbiFileNotFound(parent _ContractException, message log.Message) *AbiFileNotFound {
	return &AbiFileNotFound{parent, log.Messages{message}}
}

func (e AbiFileNotFound) Code() int64 {
	return 3160010
}

func (e AbiFileNotFound) Name() string {
	return AbiFileNotFoundName
}

func (e AbiFileNotFound) What() string {
	return "No abi file found"
}

func (e *AbiFileNotFound) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AbiFileNotFound) GetLog() log.Messages {
	return e.Elog
}

func (e AbiFileNotFound) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e AbiFileNotFound) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e AbiFileNotFound) String() string {
	return e.DetailMessage()
}

func (e AbiFileNotFound) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3160010,
		Name: AbiFileNotFoundName,
		What: "No abi file found",
	}

	return json.Marshal(except)
}

func (e AbiFileNotFound) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AbiFileNotFound):
		callback(&e)
		return true
	case func(AbiFileNotFound):
		callback(e)
		return true
	default:
		return false
	}
}
