// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var BlockFromTheFutureName = reflect.TypeOf(BlockFromTheFuture{}).Name()

type BlockFromTheFuture struct {
	_BlockValidateException
	Elog log.Messages
}

func NewBlockFromTheFuture(parent _BlockValidateException, message log.Message) *BlockFromTheFuture {
	return &BlockFromTheFuture{parent, log.Messages{message}}
}

func (e BlockFromTheFuture) Code() int64 {
	return 3030007
}

func (e BlockFromTheFuture) Name() string {
	return BlockFromTheFutureName
}

func (e BlockFromTheFuture) What() string {
	return "Block is from the future"
}

func (e *BlockFromTheFuture) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e BlockFromTheFuture) GetLog() log.Messages {
	return e.Elog
}

func (e BlockFromTheFuture) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e BlockFromTheFuture) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e BlockFromTheFuture) String() string {
	return e.DetailMessage()
}

func (e BlockFromTheFuture) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3030007,
		Name: BlockFromTheFutureName,
		What: "Block is from the future",
	}

	return json.Marshal(except)
}

func (e BlockFromTheFuture) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*BlockFromTheFuture):
		callback(&e)
		return true
	case func(BlockFromTheFuture):
		callback(e)
		return true
	default:
		return false
	}
}
