// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ParseErrorExceptionName = reflect.TypeOf(ParseErrorException{}).Name()

type ParseErrorException struct {
	Exception
	Elog log.Messages
}

func NewParseErrorException(parent Exception, message log.Message) *ParseErrorException {
	return &ParseErrorException{parent, log.Messages{message}}
}

func (e ParseErrorException) Code() int64 {
	return ParseErrorExceptionCode
}

func (e ParseErrorException) Name() string {
	return ParseErrorExceptionName
}

func (e ParseErrorException) What() string {
	return "Parse Error"
}

func (e *ParseErrorException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ParseErrorException) GetLog() log.Messages {
	return e.Elog
}

func (e ParseErrorException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e ParseErrorException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e ParseErrorException) String() string {
	return e.DetailMessage()
}

func (e ParseErrorException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: ParseErrorExceptionCode,
		Name: ParseErrorExceptionName,
		What: "Parse Error",
	}

	return json.Marshal(except)
}

func (e ParseErrorException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ParseErrorException):
		callback(&e)
		return true
	case func(ParseErrorException):
		callback(e)
		return true
	default:
		return false
	}
}
