// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var UnpackExceptionName = reflect.TypeOf(UnpackException{}).Name()

type UnpackException struct {
	_AbiException
	Elog log.Messages
}

func NewUnpackException(parent _AbiException, message log.Message) *UnpackException {
	return &UnpackException{parent, log.Messages{message}}
}

func (e UnpackException) Code() int64 {
	return 3150013
}

func (e UnpackException) Name() string {
	return UnpackExceptionName
}

func (e UnpackException) What() string {
	return "Unpack data exception"
}

func (e *UnpackException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e UnpackException) GetLog() log.Messages {
	return e.Elog
}

func (e UnpackException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e UnpackException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e UnpackException) String() string {
	return e.DetailMessage()
}

func (e UnpackException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3150013,
		Name: UnpackExceptionName,
		What: "Unpack data exception",
	}

	return json.Marshal(except)
}

func (e UnpackException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*UnpackException):
		callback(&e)
		return true
	case func(UnpackException):
		callback(e)
		return true
	default:
		return false
	}
}
