// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var FailToResolveHostName = reflect.TypeOf(FailToResolveHost{}).Name()

type FailToResolveHost struct {
	_HttpException
	Elog log.Messages
}

func NewFailToResolveHost(parent _HttpException, message log.Message) *FailToResolveHost {
	return &FailToResolveHost{parent, log.Messages{message}}
}

func (e FailToResolveHost) Code() int64 {
	return 3200004
}

func (e FailToResolveHost) Name() string {
	return FailToResolveHostName
}

func (e FailToResolveHost) What() string {
	return "fail to resolve host"
}

func (e *FailToResolveHost) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e FailToResolveHost) GetLog() log.Messages {
	return e.Elog
}

func (e FailToResolveHost) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e FailToResolveHost) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e FailToResolveHost) String() string {
	return e.DetailMessage()
}

func (e FailToResolveHost) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3200004,
		Name: FailToResolveHostName,
		What: "fail to resolve host",
	}

	return json.Marshal(except)
}

func (e FailToResolveHost) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*FailToResolveHost):
		callback(&e)
		return true
	case func(FailToResolveHost):
		callback(e)
		return true
	default:
		return false
	}
}
