// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var SetExactCodeName = reflect.TypeOf(SetExactCode{}).Name()

type SetExactCode struct {
	_ContractException
	Elog log.Messages
}

func NewSetExactCode(parent _ContractException, message log.Message) *SetExactCode {
	return &SetExactCode{parent, log.Messages{message}}
}

func (e SetExactCode) Code() int64 {
	return 3160008
}

func (e SetExactCode) Name() string {
	return SetExactCodeName
}

func (e SetExactCode) What() string {
	return "Contract is already running this version of code"
}

func (e *SetExactCode) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e SetExactCode) GetLog() log.Messages {
	return e.Elog
}

func (e SetExactCode) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e SetExactCode) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e SetExactCode) String() string {
	return e.DetailMessage()
}

func (e SetExactCode) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3160008,
		Name: SetExactCodeName,
		What: "Contract is already running this version of code",
	}

	return json.Marshal(except)
}

func (e SetExactCode) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*SetExactCode):
		callback(&e)
		return true
	case func(SetExactCode):
		callback(e)
		return true
	default:
		return false
	}
}
