// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TxNoAuthsName = reflect.TypeOf(TxNoAuths{}).Name()

type TxNoAuths struct {
	_TransactionException
	Elog log.Messages
}

func NewTxNoAuths(parent _TransactionException, message log.Message) *TxNoAuths {
	return &TxNoAuths{parent, log.Messages{message}}
}

func (e TxNoAuths) Code() int64 {
	return 3040003
}

func (e TxNoAuths) Name() string {
	return TxNoAuthsName
}

func (e TxNoAuths) What() string {
	return "Transaction should have at least one required authority"
}

func (e *TxNoAuths) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TxNoAuths) GetLog() log.Messages {
	return e.Elog
}

func (e TxNoAuths) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TxNoAuths) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TxNoAuths) String() string {
	return e.DetailMessage()
}

func (e TxNoAuths) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3040003,
		Name: TxNoAuthsName,
		What: "Transaction should have at least one required authority",
	}

	return json.Marshal(except)
}

func (e TxNoAuths) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TxNoAuths):
		callback(&e)
		return true
	case func(TxNoAuths):
		callback(e)
		return true
	default:
		return false
	}
}
