// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AccountNameExistsExceptionName = reflect.TypeOf(AccountNameExistsException{}).Name()

type AccountNameExistsException struct {
	_ActionValidateException
	Elog log.Messages
}

func NewAccountNameExistsException(parent _ActionValidateException, message log.Message) *AccountNameExistsException {
	return &AccountNameExistsException{parent, log.Messages{message}}
}

func (e AccountNameExistsException) Code() int64 {
	return 3050001
}

func (e AccountNameExistsException) Name() string {
	return AccountNameExistsExceptionName
}

func (e AccountNameExistsException) What() string {
	return "Account name already exists"
}

func (e *AccountNameExistsException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AccountNameExistsException) GetLog() log.Messages {
	return e.Elog
}

func (e AccountNameExistsException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e AccountNameExistsException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e AccountNameExistsException) String() string {
	return e.DetailMessage()
}

func (e AccountNameExistsException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3050001,
		Name: AccountNameExistsExceptionName,
		What: "Account name already exists",
	}

	return json.Marshal(except)
}

func (e AccountNameExistsException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AccountNameExistsException):
		callback(&e)
		return true
	case func(AccountNameExistsException):
		callback(e)
		return true
	default:
		return false
	}
}
