// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AesExceptionName = reflect.TypeOf(AesException{}).Name()

type AesException struct {
	Exception
	Elog log.Messages
}

func NewAesException(parent Exception, message log.Message) *AesException {
	return &AesException{parent, log.Messages{message}}
}

func (e AesException) Code() int64 {
	return UdtErrorCode
}

func (e AesException) Name() string {
	return AesExceptionName
}

func (e AesException) What() string {
	return "AES error"
}

func (e *AesException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AesException) GetLog() log.Messages {
	return e.Elog
}

func (e AesException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e AesException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e AesException) String() string {
	return e.DetailMessage()
}

func (e AesException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: UdtErrorCode,
		Name: AesExceptionName,
		What: "AES error",
	}

	return json.Marshal(except)
}

func (e AesException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AesException):
		callback(&e)
		return true
	case func(AesException):
		callback(e)
		return true
	default:
		return false
	}
}
