// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var TransactionTypeExceptionName = reflect.TypeOf(TransactionTypeException{}).Name()

type TransactionTypeException struct {
	_ChainException
	Elog log.Messages
}

func NewTransactionTypeException(parent _ChainException, message log.Message) *TransactionTypeException {
	return &TransactionTypeException{parent, log.Messages{message}}
}

func (e TransactionTypeException) Code() int64 {
	return 3010006
}

func (e TransactionTypeException) Name() string {
	return TransactionTypeExceptionName
}

func (e TransactionTypeException) What() string {
	return "Invalid transaction"
}

func (e *TransactionTypeException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e TransactionTypeException) GetLog() log.Messages {
	return e.Elog
}

func (e TransactionTypeException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e TransactionTypeException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e TransactionTypeException) String() string {
	return e.DetailMessage()
}

func (e TransactionTypeException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3010006,
		Name: TransactionTypeExceptionName,
		What: "Invalid transaction",
	}

	return json.Marshal(except)
}

func (e TransactionTypeException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*TransactionTypeException):
		callback(&e)
		return true
	case func(TransactionTypeException):
		callback(e)
		return true
	default:
		return false
	}
}
