// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var WastFileNotFoundName = reflect.TypeOf(WastFileNotFound{}).Name()

type WastFileNotFound struct {
	_ContractException
	Elog log.Messages
}

func NewWastFileNotFound(parent _ContractException, message log.Message) *WastFileNotFound {
	return &WastFileNotFound{parent, log.Messages{message}}
}

func (e WastFileNotFound) Code() int64 {
	return 3160009
}

func (e WastFileNotFound) Name() string {
	return WastFileNotFoundName
}

func (e WastFileNotFound) What() string {
	return "No wast file found"
}

func (e *WastFileNotFound) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e WastFileNotFound) GetLog() log.Messages {
	return e.Elog
}

func (e WastFileNotFound) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e WastFileNotFound) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e WastFileNotFound) String() string {
	return e.DetailMessage()
}

func (e WastFileNotFound) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3160009,
		Name: WastFileNotFoundName,
		What: "No wast file found",
	}

	return json.Marshal(except)
}

func (e WastFileNotFound) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*WastFileNotFound):
		callback(&e)
		return true
	case func(WastFileNotFound):
		callback(e)
		return true
	default:
		return false
	}
}
