// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var FileNotFoundExceptionName = reflect.TypeOf(FileNotFoundException{}).Name()

type FileNotFoundException struct {
	Exception
	Elog log.Messages
}

func NewFileNotFoundException(parent Exception, message log.Message) *FileNotFoundException {
	return &FileNotFoundException{parent, log.Messages{message}}
}

func (e FileNotFoundException) Code() int64 {
	return FileNotFoundExceptionCode
}

func (e FileNotFoundException) Name() string {
	return FileNotFoundExceptionName
}

func (e FileNotFoundException) What() string {
	return "File Not Found"
}

func (e *FileNotFoundException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e FileNotFoundException) GetLog() log.Messages {
	return e.Elog
}

func (e FileNotFoundException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e FileNotFoundException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e FileNotFoundException) String() string {
	return e.DetailMessage()
}

func (e FileNotFoundException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: FileNotFoundExceptionCode,
		Name: FileNotFoundExceptionName,
		What: "File Not Found",
	}

	return json.Marshal(except)
}

func (e FileNotFoundException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*FileNotFoundException):
		callback(&e)
		return true
	case func(FileNotFoundException):
		callback(e)
		return true
	default:
		return false
	}
}
