// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var HttpRequestFailName = reflect.TypeOf(HttpRequestFail{}).Name()

type HttpRequestFail struct {
	_HttpException
	Elog log.Messages
}

func NewHttpRequestFail(parent _HttpException, message log.Message) *HttpRequestFail {
	return &HttpRequestFail{parent, log.Messages{message}}
}

func (e HttpRequestFail) Code() int64 {
	return 3200005
}

func (e HttpRequestFail) Name() string {
	return HttpRequestFailName
}

func (e HttpRequestFail) What() string {
	return "http request fail"
}

func (e *HttpRequestFail) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e HttpRequestFail) GetLog() log.Messages {
	return e.Elog
}

func (e HttpRequestFail) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e HttpRequestFail) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("]")
		buffer.WriteString("\n")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e HttpRequestFail) String() string {
	return e.DetailMessage()
}

func (e HttpRequestFail) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3200005,
		Name: HttpRequestFailName,
		What: "http request fail",
	}

	return json.Marshal(except)
}

func (e HttpRequestFail) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*HttpRequestFail):
		callback(&e)
		return true
	case func(HttpRequestFail):
		callback(e)
		return true
	default:
		return false
	}
}
