// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var AbiRecursionDepthExceptionName = reflect.TypeOf(AbiRecursionDepthException{}).Name()

type AbiRecursionDepthException struct {
	_AbiException
	Elog log.Messages
}

func NewAbiRecursionDepthException(parent _AbiException, message log.Message) *AbiRecursionDepthException {
	return &AbiRecursionDepthException{parent, log.Messages{message}}
}

func (e AbiRecursionDepthException) Code() int64 {
	return 3150011
}

func (e AbiRecursionDepthException) Name() string {
	return AbiRecursionDepthExceptionName
}

func (e AbiRecursionDepthException) What() string {
	return "ABI recursive definition has exceeded the max recursion depth"
}

func (e *AbiRecursionDepthException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e AbiRecursionDepthException) GetLog() log.Messages {
	return e.Elog
}

func (e AbiRecursionDepthException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e AbiRecursionDepthException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e AbiRecursionDepthException) String() string {
	return e.DetailMessage()
}

func (e AbiRecursionDepthException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3150011,
		Name: AbiRecursionDepthExceptionName,
		What: "ABI recursive definition has exceeded the max recursion depth",
	}

	return json.Marshal(except)
}

func (e AbiRecursionDepthException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*AbiRecursionDepthException):
		callback(&e)
		return true
	case func(AbiRecursionDepthException):
		callback(e)
		return true
	default:
		return false
	}
}
