// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var DivideByZeroExceptionName = reflect.TypeOf(DivideByZeroException{}).Name()

type DivideByZeroException struct {
	Exception
	Elog log.Messages
}

func NewDivideByZeroException(parent Exception, message log.Message) *DivideByZeroException {
	return &DivideByZeroException{parent, log.Messages{message}}
}

func (e DivideByZeroException) Code() int64 {
	return DivideByZeroCode
}

func (e DivideByZeroException) Name() string {
	return DivideByZeroExceptionName
}

func (e DivideByZeroException) What() string {
	return "Integer Divide By Zero"
}

func (e *DivideByZeroException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e DivideByZeroException) GetLog() log.Messages {
	return e.Elog
}

func (e DivideByZeroException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e DivideByZeroException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e DivideByZeroException) String() string {
	return e.DetailMessage()
}

func (e DivideByZeroException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: DivideByZeroCode,
		Name: DivideByZeroExceptionName,
		What: "Integer Divide By Zero",
	}

	return json.Marshal(except)
}

func (e DivideByZeroException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*DivideByZeroException):
		callback(&e)
		return true
	case func(DivideByZeroException):
		callback(e)
		return true
	default:
		return false
	}
}
