// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/eosspark/eos-go/log"
)

// template type Exception(PARENT,CODE,WHAT)

var MissingHistoryApiPluginExceptionName = reflect.TypeOf(MissingHistoryApiPluginException{}).Name()

type MissingHistoryApiPluginException struct {
	_PluginException
	Elog log.Messages
}

func NewMissingHistoryApiPluginException(parent _PluginException, message log.Message) *MissingHistoryApiPluginException {
	return &MissingHistoryApiPluginException{parent, log.Messages{message}}
}

func (e MissingHistoryApiPluginException) Code() int64 {
	return 3110003
}

func (e MissingHistoryApiPluginException) Name() string {
	return MissingHistoryApiPluginExceptionName
}

func (e MissingHistoryApiPluginException) What() string {
	return "Missing History API Plugin"
}

func (e *MissingHistoryApiPluginException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e MissingHistoryApiPluginException) GetLog() log.Messages {
	return e.Elog
}

func (e MissingHistoryApiPluginException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); msg != "" {
			return msg
		}
	}
	return e.String()
}

func (e MissingHistoryApiPluginException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteString(" ")
	buffer.WriteString(e.Name())
	buffer.WriteString(": ")
	buffer.WriteString(e.What())
	buffer.WriteString("\n")
	for _, l := range e.Elog {
		buffer.WriteString("[")
		buffer.WriteString(l.GetMessage())
		buffer.WriteString("] ")
		buffer.WriteString(l.GetContext().String())
		buffer.WriteString("\n")
	}
	return buffer.String()
}

func (e MissingHistoryApiPluginException) String() string {
	return e.DetailMessage()
}

func (e MissingHistoryApiPluginException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 3110003,
		Name: MissingHistoryApiPluginExceptionName,
		What: "Missing History API Plugin",
	}

	return json.Marshal(except)
}

func (e MissingHistoryApiPluginException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*MissingHistoryApiPluginException):
		callback(&e)
		return true
	case func(MissingHistoryApiPluginException):
		callback(e)
		return true
	default:
		return false
	}
}
