package main

const url = "http://127.0.0.1:8888/"
const walletUrl = "http://127.0.0.1:8900/"

const chainFuncBase string = "/v1/chain"
const getInfoFunc string = chainFuncBase + "/get_info"
const pushTxnFunc string = chainFuncBase + "/push_transaction"
const pushTxnsFunc string = chainFuncBase + "/push_transactions"
const jsonToBinFunc string = chainFuncBase + "/abi_json_to_bin"
const getBlockFunc string = chainFuncBase + "/get_block"
const getBlockHeaderStateFunc string = chainFuncBase + "/get_block_header_state"
const getAccountFunc string = chainFuncBase + "/get_account"
const getTableFunc string = chainFuncBase + "/get_table_rows"
const getCodeFunc string = chainFuncBase + "/get_code"
const getAbiFunc string = chainFuncBase + "/get_abi"
const getRawCodeAndAbiFunc string = chainFuncBase + "/get_raw_code_and_abi"
const getCurrencyBalanceFunc string = chainFuncBase + "/get_currency_balance"
const getCurrencyStatsFunc string = chainFuncBase + "/get_currency_stats"
const getProducersFunc string = chainFuncBase + "/get_producers"
const getScheduleFunc string = chainFuncBase + "/get_producer_schedule"
const getRequiredKeys string = chainFuncBase + "/get_required_keys"

const historyFuncBase string = "/v1/history"
const getActionsFunc string = historyFuncBase + "/get_actions"
const getTransactionFunc string = historyFuncBase + "/get_transaction"
const getKeyAccountsFunc string = historyFuncBase + "/get_key_accounts"
const getControlledAccountsFunc string = historyFuncBase + "/get_controlled_accounts"

const accountHistoryFuncBase string = "/v1/account_history"
const getTransactionsFunc string = accountHistoryFuncBase + "/get_transactions"

const netFuncBase string = "/v1/net"
const netConnect string = netFuncBase + "/connect"
const netDisconnect string = netFuncBase + "/disconnect"
const netStatus string = netFuncBase + "/status"
const netConnections string = netFuncBase + "/connections"

const walletFuncBase string = "/v1/wallet"
const walletCreate string = walletFuncBase + "/create"
const walletOpen string = walletFuncBase + "/open"
const walletList string = walletFuncBase + "/list_wallets"
const walletListKeys string = walletFuncBase + "/list_keys"
const walletPublicKeys string = walletFuncBase + "/get_public_keys"
const walletLock string = walletFuncBase + "/lock"
const walletLockAll string = walletFuncBase + "/lock_all"
const walletUnlock string = walletFuncBase + "/unlock"
const walletImportKey string = walletFuncBase + "/import_key"
const walletRemoveKey string = walletFuncBase + "/remove_key"
const walletCreateKey string = walletFuncBase + "/create_key"
const walletSignTrx string = walletFuncBase + "/sign_transaction"

const keosdStop string = "/v1/keosd/stop"
